OPERATE_INCOME double default null comment '一、营业收入(元)',
zb[0].TOTAL_ASSETS double default null comment '总资产',
INTEREST_NI double default null comment '    利息净收入(元)',
zb[0].TOTAL_CURRENT_ASSETS double default null comment '    流动资产',
FEE_COMMISSION_NI double default null comment '    手续费及佣金净收入(元)',
zb[0].TOTAL_NONCURRENT_ASSETS double default null comment '    非流动资产',
INVEST_INCOME double default null comment '    投资收益(元)',
zb[0].TOTAL_LIABILITIES double default null comment '总负债金额',
FAIRVALUE_CHANGE_INCOME double default null comment '    公允价值变动收益(元)',
zb[0].TOTAL_CURRENT_LIAB double default null comment '    流动负债',
EXCHANGE_INCOME double default null comment '    汇兑收益(元)',
zb[0].TOTAL_NONCURRENT_LIAB double default null comment '    非流动负债',
OTHER_BUSINESS_INCOME double default null comment '    其他业务收入(元)',
ASSET_DISPOSAL_INCOME double default null comment '    资产处置收益(元)',
OTHER_INCOME double default null comment '    其他收益(元)',
OPERATE_EXPENSE double default null comment '二、营业支出(元)',
OPERATE_TAX_ADD double default null comment '    税金及附加(元)',
BUSINESS_MANAGE_EXPENSE double default null comment '    业务及管理费(元)',
ASSET_IMPAIRMENT_LOSS double default null comment '    资产减值损失(元)',
CREDIT_IMPAIRMENT_LOSS double default null comment '    信用减值损失(元)',
OTHER_BUSINESS_COST double default null comment '    其他业务成本(元)',
OPERATE_PROFIT double default null comment '三、营业利润(元)',
NONBUSINESS_INCOME double default null comment '    加:营业外收入(元)',
NONBUSINESS_EXPENSE double default null comment '    减:营业外支出(元)',
TOTAL_PROFIT double default null comment '四、利润总额(元)',
INCOME_TAX double default null comment '    减:所得税费用(元)',
NETPROFIT double default null comment '五、净利润(元)',
TOTAL_OPERATE_INCOME double default null comment '一、营业总收入(元)',
TOTAL_OPERATE_COST double default null comment '二、营业总成本(元)',
OPERATE_COST double default null comment '    营业成本(元)',
TOTAL_EXPENSE double default null comment '    期间费用(元)',
SALE_EXPENSE double default null comment '        销售费用(元)',
MANAGE_EXPENSE double default null comment '        管理费用(元)',
RESEARCH_EXPENSE double default null comment '        研发费用(元)',
FINANCE_EXPENSE double default null comment '        财务费用(元)',
CREDIT_IMPAIRMENT_INCOME double default null comment '    信用减值损失(元)',
ASSET_IMPAIRMENT_INCOME double default null comment '    资产减值损失(元)',
EARNED_PREMIUM double default null comment '    已赚保费(元)',
FAIRVALUE_CHANGE double default null comment '    公允价值变动收益(元)',
SURRENDER_VALUE double default null comment '    退保金(元)',
COMPENSATE_EXPENSE double default null comment '    赔付支出(元)',
AMORTIZE_COMPENSATE_EXPENSE double default null comment '        减:摊回赔付支出(元)',
EXTRACT_INSURANCE_RESERVE double default null comment '    提取保险责任准备金(元)',
AMORTIZE_INSURANCE_RESERVE double default null comment '        减:摊回保险责任准备金(元)',
POLICY_BONUS_EXPENSE double default null comment '    保单红利支出(元)',
FEE_COMMISSION_EXPENSE double default null comment '    手续费及佣金支出(元)',
