/*
 财务分析-利润
*/
drop table if exists `inv_finance_lr`;
create table `inv_finance_lr`(
    `id` bigint not null auto_increment comment 'id',
    `security_code` varchar(10) character set utf8mb4 collate utf8mb4_general_ci not null comment '股票代码',
    `report_type` varchar(10) character set utf8mb4 collate utf8mb4_general_ci not null comment '报告类型',
    `report_date` datetime default null comment '报告日期',


    `OPERATE_INCOME` double default null comment '营业收入总额',
    `OPERATE_INCOME_YOY` double default null comment '营业收入总额(环比%)',
    `INTEREST_NI` double default null comment '利息净收入',
    `INTEREST_NI_YOY` double default null comment '利息净收入(环比%)',
    `INTEREST_INCOME` double default null comment '利息收入',
    `INTEREST_INCOME_YOY` double default null comment '利息收入(环比%)',
    `INTEREST_EXPENSE` double default null comment '利息支出',
    `INTEREST_EXPENSE_YOY` double default null comment '利息支出(环比%)',
    `FEE_COMMISSION_NI` double default null comment '手续费及佣金净收入',
    `FEE_COMMISSION_NI_YOY` double default null comment '手续费及佣金净收入(环比%)',
    `FEE_COMMISSION_INCOME` double default null comment '手续费及佣金收入',
    `FEE_COMMISSION_INCOME_YOY` double default null comment '手续费及佣金收入(环比%)',
    `FEE_COMMISSION_EXPENSE` double default null comment '手续费及佣金支出',
    `FEE_COMMISSION_EXPENSE_YOY` double default null comment '手续费及佣金支出(环比%)',
    `INVEST_INCOME` double default null comment '投资收益',
    `INVEST_INCOME_YOY` double default null comment '投资收益(环比%)',
    `INVEST_JOINT_INCOME` double default null comment '对联营企业和合营企业的投资收益',
    `INVEST_JOINT_INCOME_YOY` double default null comment '对联营企业和合营企业的投资收益(环比%)',
    `FAIRVALUE_CHANGE_INCOME` double default null comment '公允价值变动收益',
    `FAIRVALUE_CHANGE_INCOME_YOY` double default null comment '公允价值变动收益(环比%)',
    `EXCHANGE_INCOME` double default null comment '汇兑损失',
    `EXCHANGE_INCOME_YOY` double default null comment '汇兑损失(环比%)',
    `OTHER_BUSINESS_INCOME` double default null comment '其他业务收入',
    `OTHER_BUSINESS_INCOME_YOY` double default null comment '其他业务收入(环比%)',
    `ASSET_DISPOSAL_INCOME` double default null comment ' null',
    `ASSET_DISPOSAL_INCOME_YOY` double default null comment ' null',
    `OTHER_INCOME` double default null comment ' null',
    `OTHER_INCOME_YOY` double default null comment ' null',
    `OPERATE_INCOME_OTHER` double default null comment ' null',
    `OPERATE_INCOME_OTHER_YOY` double default null comment ' null',
    `OPERATE_INCOME_BALANCE` double default null comment ' 0',
    `OPERATE_INCOME_BALANCE_YOY` double default null comment ' null',
    `OPERATE_EXPENSE` double default null comment '营业支出总额',
    `OPERATE_EXPENSE_YOY` double default null comment '营业支出总额(环比%)',
    `OPERATE_TAX_ADD` double default null comment '税金及附加',
    `OPERATE_TAX_ADD_YOY` double default null comment '税金及附加(环比%)',
    `BUSINESS_MANAGE_EXPENSE` double default null comment '业务及管理费',
    `BUSINESS_MANAGE_EXPENSE_YOY` double default null comment '业务及管理费(环比%)',
    `ASSET_IMPAIRMENT_LOSS` double default null comment ' null',
    `ASSET_IMPAIRMENT_LOSS_YOY` double default null comment ' null',
    `CREDIT_IMPAIRMENT_LOSS` double default null comment '信用减值损失',
    `CREDIT_IMPAIRMENT_LOSS_YOY` double default null comment '信用减值损失(环比%)',
    `OTHER_BUSINESS_COST` double default null comment '其他业务成本',
    `OTHER_BUSINESS_COST_YOY` double default null comment '其他业务成本(环比%)',
    `OPERATE_EXPENSE_OTHER` double default null comment ' null',
    `OPERATE_EXPENSE_OTHER_YOY` double default null comment ' null',
    `OPERATE_EXPENSE_BALANCE` double default null comment ' null',
    `OPERATE_EXPENSE_BALANCE_YOY` double default null comment ' null',
    `OPERATE_PROFIT_OTHER` double default null comment ' null',
    `OPERATE_PROFIT_OTHER_YOY` double default null comment ' null',
    `OPERATE_PROFIT_BALANCE` double default null comment ' null',
    `OPERATE_PROFIT_BALANCE_YOY` double default null comment ' null',
    `OPERATE_PROFIT` double default null comment '营业利润',
    `OPERATE_PROFIT_YOY` double default null comment '营业利润(环比%)',
    `NONBUSINESS_INCOME` double default null comment '营业外收入',
    `NONBUSINESS_INCOME_YOY` double default null comment '营业外收入(环比%)',
    `NONCURRENT_DISPOSAL_INCOME` double default null comment ' null',
    `NONCURRENT_DISPOSAL_INCOME_YOY` double default null comment ' null',
    `NONBUSINESS_EXPENSE` double default null comment '营业外支出',
    `NONBUSINESS_EXPENSE_YOY` double default null comment '营业外支出(环比%)',
    `NONCURRENT_DISPOSAL_LOSS` double default null comment ' null',
    `NONCURRENT_DISPOSAL_LOSS_YOY` double default null comment ' null',
    `EFFECT_TP_OTHER` double default null comment ' null',
    `EFFECT_TP_OTHER_YOY` double default null comment ' null',
    `TOTAL_PROFIT_BALANCE` double default null comment ' 0',
    `TOTAL_PROFIT_BALANCE_YOY` double default null comment ' null',
    `TOTAL_PROFIT` double default null comment '利润总额',
    `TOTAL_PROFIT_YOY` double default null comment '利润总额(环比%)',
    `INCOME_TAX` double default null comment '所得税',
    `INCOME_TAX_YOY` double default null comment '所得税(环比%)',
    `EFFECT_NETPROFIT_OTHER` double default null comment ' null',
    `EFFECT_NETPROFIT_OTHER_YOY` double default null comment ' null',
    `EFFECT_NETPROFIT_BALANCE` double default null comment ' null',
    `EFFECT_NETPROFIT_BALANCE_YOY` double default null comment ' null',
    `NETPROFIT` double default null comment '净利润',
    `NETPROFIT_YOY` double default null comment '净利润(环比%)',
    `CONTINUED_NETPROFIT` double default null comment ' null',
    `CONTINUED_NETPROFIT_YOY` double default null comment ' null',
    `DISCONTINUED_NETPROFIT` double default null comment ' null',
    `DISCONTINUED_NETPROFIT_YOY` double default null comment ' null',
    `PARENT_NETPROFIT` double default null comment '归属于母公司股东的净利润',
    `PARENT_NETPROFIT_YOY` double default null comment '归属于母公司股东的净利润(环比%)',
    `MINORITY_INTEREST` double default null comment '少数股东损益',
    `MINORITY_INTEREST_YOY` double default null comment '少数股东损益(环比%)',
    `DEDUCT_PARENT_NETPROFIT` double default null comment '扣除非经常性损益后的净利润',
    `DEDUCT_PARENT_NETPROFIT_YOY` double default null comment '扣除非经常性损益后的净利润(环比%)',
    `NETPROFIT_OTHER` double default null comment ' null',
    `NETPROFIT_OTHER_YOY` double default null comment ' null',
    `NETPROFIT_BALANCE` double default null comment ' null',
    `NETPROFIT_BALANCE_YOY` double default null comment ' null',
    `BASIC_EPS` double default null comment '基本每股收益',
    `BASIC_EPS_YOY` double default null comment '基本每股收益(环比%)',
    `DILUTED_EPS` double default null comment '稀释每股收益',
    `DILUTED_EPS_YOY` double default null comment '稀释每股收益(环比%)',
    `OTHER_COMPRE_INCOME` double default null comment '其他综合收益',
    `OTHER_COMPRE_INCOME_YOY` double default null comment '其他综合收益(环比%)',
    `PARENT_OCI` double default null comment '归属于母公司股东的其他综合收益',
    `PARENT_OCI_YOY` double default null comment '归属于母公司股东的其他综合收益(环比%)',
    `MINORITY_OCI` double default null comment '归属于少数股东的其他综合收益',
    `MINORITY_OCI_YOY` double default null comment '归属于少数股东的其他综合收益(环比%)',
    `PARENT_OCI_OTHER` double default null comment ' null',
    `PARENT_OCI_OTHER_YOY` double default null comment ' null',
    `PARENT_OCI_BALANCE` double default null comment ' null',
    `PARENT_OCI_BALANCE_YOY` double default null comment ' null',
    `UNABLE_OCI` double default null comment ' -11000000',
    `UNABLE_OCI_YOY` double default null comment ' -101.0270774977',
    `SETUP_PROFIT_CHANGE` double default null comment ' -2000000',
    `SETUP_PROFIT_CHANGE_YOY` double default null comment ' -107.6923076923',
    `RIGHTLAW_UNABLE_OCI` double default null comment ' null',
    `RIGHTLAW_UNABLE_OCI_YOY` double default null comment ' null',
    `UNABLE_OCI_OTHER` double default null comment ' null',
    `UNABLE_OCI_OTHER_YOY` double default null comment ' null',
    `UNABLE_OCI_BALANCE` double default null comment ' null',
    `UNABLE_OCI_BALANCE_YOY` double default null comment ' null',
    `ABLE_OCI` double default null comment ' 1860000000',
    `ABLE_OCI_YOY` double default null comment ' -23.4252778921',
    `RIGHTLAW_ABLE_OCI` double default null comment ' -325000000',
    `RIGHTLAW_ABLE_OCI_YOY` double default null comment ' -128.8732394366',
    `AFA_FAIRVALUE_CHANGE` double default null comment ' null',
    `AFA_FAIRVALUE_CHANGE_YOY` double default null comment ' null',
    `HMI_AFA` double default null comment ' null',
    `HMI_AFA_YOY` double default null comment ' null',
    `CASHFLOW_HEDGE_VALID` double default null comment ' 103000000',
    `CASHFLOW_HEDGE_VALID_YOY` double default null comment ' 119.1489361702',
    `CONVERT_DIFF` double default null comment ' 2258000000',
    `CONVERT_DIFF_YOY` double default null comment ' 403.4946236559',
    `ABLE_OCI_OTHER` double default null comment ' -176000000',
    `ABLE_OCI_OTHER_YOY` double default null comment ' -105.3855569155',
    `ABLE_OCI_BALANCE` double default null comment ' null',
    `ABLE_OCI_BALANCE_YOY` double default null comment ' null',
    `OCI_OTHER` double default null comment ' null',
    `OCI_OTHER_YOY` double default null comment ' null',
    `OCI_BALANCE` double default null comment ' null',
    `OCI_BALANCE_YOY` double default null comment ' null',
    `TOTAL_COMPRE_INCOME` double default null comment '综合收益总额',
    `TOTAL_COMPRE_INCOME_YOY` double default null comment '综合收益总额(环比%)',
    `PARENT_TCI` double default null comment '归属于母公司股东的综合收益总额',
    `PARENT_TCI_YOY` double default null comment '归属于母公司股东的综合收益总额(环比%)',
    `MINORITY_TCI` double default null comment '归属于少数股东的综合收益总额',
    `MINORITY_TCI_YOY` double default null comment '归属于少数股东的综合收益总额(环比%)',
    `TCI_BALANCE` double default null comment ' null',
    `TCI_BALANCE_YOY` double default null comment ' null',
    `EFFECT_TCI_BALANCE` double default null comment ' null',
    `EFFECT_TCI_BALANCE_YOY` double default null comment ' null',
    `OTHERRIGHT_FAIRVALUE_CHANGE` double default null comment ' -9000000',
    `OTHERRIGHT_FAIRVALUE_CHANGE_YOY` double default null comment ' -100.8612440191',
    `CREDITRISK_FAIRVALUE_CHANGE` double default null comment ' null',
    `CREDITRISK_FAIRVALUE_CHANGE_YOY` double default null comment ' null',
    `CREDITOR_FAIRVALUE_CHANGE` double default null comment ' null',
    `CREDITOR_FAIRVALUE_CHANGE_YOY` double default null comment ' null',
    `FINANCE_OCI_AMT` double default null comment ' null',
    `FINANCE_OCI_AMT_YOY` double default null comment ' null',
    `CREDITOR_IMPAIRMENT_RESERVE` double default null comment ' null',
    `CREDITOR_IMPAIRMENT_RESERVE_YOY` double default null comment ' null',
    `ACF_END_INCOME` double default null comment ' 158000000',
    `ACF_END_INCOME_YOY` double default null comment ' 15700',
    `OPINION_TYPE` double default null comment ' null',
    `OSOPINION_TYPE` double default null comment ' null',





    `PARENT_OCI_QOQ` double default null comment '-',
    `EXTRACT_INSURANCE_RESERVE` double default null comment '-',
    `EXTRACT_INSURANCE_RESERVE_YOY` double default null comment '(环比%)',
    `ASSET_MANAGE_NI` double default null comment '-',
    `ASSET_MANAGE_NI_YOY` double default null comment '(环比%)',
    `EXTRACT_UNEXPIRE_RESERVE` double default null comment '-',
    `EXTRACT_UNEXPIRE_RESERVE_YOY` double default null comment '(环比%)',
    `TCI_BALANCE_QOQ` double default null comment '-',
    `OPERATE_EXPENSE_QOQ` double default null comment '-',
    `UNABLE_OCI_BALANCE_QOQ` double default null comment '-',
    `NET_CONTRACT_RESERVE` double default null comment '-',
    `NET_CONTRACT_RESERVE_YOY` double default null comment '(环比%)',
    `EARNED_PREMIUM_BALANCE` double default null comment '-',
    `EARNED_PREMIUM_BALANCE_YOY` double default null comment '(环比%)',
    `MANAGE_EXPENSE` double default null comment '-',
    `MANAGE_EXPENSE_YOY` double default null comment '(环比%)',
    `BANK_INTEREST_NI_QOQ` double default null comment '-',
    `ABLE_OCI_BALANCE_QOQ` double default null comment '-',
    `EXTRACT_UNEXPIRE_RESERVE_QOQ` double default null comment '-',
    `OPERATE_COST` double default null comment '-',
    `OPERATE_COST_YOY` double default null comment '(环比%)',
    `BANK_INTEREST_EXPENSE` double default null comment '-',
    `BANK_INTEREST_EXPENSE_YOY` double default null comment '(环比%)',
    `CREDITOR_IMPAIRMENT_RESERVE_QOQ` double default null comment '-',
    `OPERATE_PROFIT_BALANCE_QOQ` double default null comment '-',
    `POLICY_BONUS_EXPENSE_QOQ` double default null comment '-',
    `FAIRVALUE_CHANGE` double default null comment '-',
    `FAIRVALUE_CHANGE_YOY` double default null comment '(环比%)',
    `FUND_MANAGE_NI_QOQ` double default null comment '-',
    `ABLE_OCI_OTHER_QOQ` double default null comment '-',
    `EFFECT_TCI_BALANCE` double default null comment '-',
    `EFFECT_TCI_BALANCE_YOY` double default null comment '(环比%)',
    `FEE_COMMISSION_EXPENSE` double default null comment '-',
    `FEE_COMMISSION_EXPENSE_YOY` double default null comment '(环比%)',
    `OPINION_TYPE` double default null comment '-',
    `ASSET_MANAGE_NI_QOQ` double default null comment '-',
    `AMORTIZE_COMPENSATE_EXPENSE` double default null comment '-',
    `AMORTIZE_COMPENSATE_EXPENSE_YOY` double default null comment '(环比%)',
    `TOTAL_OPERATE_COST` double default null comment '-',
    `TOTAL_OPERATE_COST_YOY` double default null comment '(环比%)',
    `OTHER_BUSINESS_COST_QOQ` double default null comment '-',
    `AGENT_SECURITY_NI_QOQ` double default null comment '-',
    `OPERATE_INCOME_BALANCE_QOQ` double default null comment '-',
    `ACF_END_INCOME_QOQ` double default null comment '-',
    `DILUTED_EPS_QOQ` double default null comment '-',
    `PARENT_OCI_OTHER_QOQ` double default null comment '-',
    `COMMISSION_NI_OTHER` double default null comment '-',
    `COMMISSION_NI_OTHER_YOY` double default null comment '(环比%)',
    `TOI_OTHER_QOQ` double default null comment '-',
    `FE_INTEREST_EXPENSE_QOQ` double default null comment '-',
    `TOTAL_COMPRE_INCOME` double default null comment '-',
    `TOTAL_COMPRE_INCOME_YOY` double default null comment '(环比%)',
    `FINANCE_OCI_AMT_QOQ` double default null comment '-',
    `ABLE_OCI_BALANCE` double default null comment '-',
    `ABLE_OCI_BALANCE_YOY` double default null comment '(环比%)',
    `NONCURRENT_DISPOSAL_LOSS_QOQ` double default null comment '-',
    `DISCONTINUED_NETPROFIT` double default null comment '-',
    `DISCONTINUED_NETPROFIT_YOY` double default null comment '(环比%)',
    `AGENT_SECURITY_NI` double default null comment '-',
    `AGENT_SECURITY_NI_YOY` double default null comment '(环比%)',
    `OCI_BALANCE_QOQ` double default null comment '-',
    `NETPROFIT_QOQ` double default null comment '-',
    `MANAGE_EXPENSE_QOQ` double default null comment '-',
    `ASSET_IMPAIRMENT_INCOME_QOQ` double default null comment '-',
    `ORG_CODE` double default null comment '-',
    `NONCURRENT_DISPOSAL_INCOME_QOQ` double default null comment '-',
    `OPERATE_EXPENSE_BALANCE_QOQ` double default null comment '-',
    `RECOMMEND_NI` double default null comment '-',
    `RECOMMEND_NI_YOY` double default null comment '(环比%)',
    `EFFECT_NETPROFIT_BALANCE` double default null comment '-',
    `EFFECT_NETPROFIT_BALANCE_YOY` double default null comment '(环比%)',
    `FE_INTEREST_EXPENSE` double default null comment '-',
    `FE_INTEREST_EXPENSE_YOY` double default null comment '(环比%)',
    `NONBUSINESS_EXPENSE_QOQ` double default null comment '-',
    `RIGHTLAW_ABLE_OCI` double default null comment '-',
    `RIGHTLAW_ABLE_OCI_YOY` double default null comment '(环比%)',
    `INVEST_JOINT_INCOME_QOQ` double default null comment '-',
    `UNCONFIRM_INVEST_LOSS` double default null comment '-',
    `UNCONFIRM_INVEST_LOSS_YOY` double default null comment '(环比%)',
    `PRECOMBINE_TCI` double default null comment '-',
    `PRECOMBINE_TCI_YOY` double default null comment '(环比%)',
    `OTHER_BUSINESS_INCOME` double default null comment '-',
    `OTHER_BUSINESS_INCOME_YOY` double default null comment '(环比%)',
    `NETPROFIT_BALANCE` double default null comment '-',
    `NETPROFIT_BALANCE_YOY` double default null comment '(环比%)',
    `REINSURE_PREMIUM` double default null comment '-',
    `REINSURE_PREMIUM_YOY` double default null comment '(环比%)',
    `UNINSURANCE_CNI_QOQ` double default null comment '-',
    `AMORTIZE_COMPENSATE_EXPENSE_QOQ` double default null comment '-',
    `NETPROFIT` double default null comment '-',
    `NETPROFIT_YOY` double default null comment '(环比%)',
    `UNABLE_OCI` double default null comment '-',
    `UNABLE_OCI_YOY` double default null comment '(环比%)',
    `REINSURE_INCOME_QOQ` double default null comment '-',
    `FAIRVALUE_CHANGE_INCOME_QOQ` double default null comment '-',
    `BANK_INTEREST_NI` double default null comment '-',
    `BANK_INTEREST_NI_YOY` double default null comment '(环比%)',
    `MINORITY_INTEREST_QOQ` double default null comment '-',
    `BUSINESS_MANAGE_EXPENSE_QOQ` double default null comment '-',
    `PRECOMBINE_PROFIT` double default null comment '-',
    `PRECOMBINE_PROFIT_YOY` double default null comment '(环比%)',
    `ASSET_IMPAIRMENT_INCOME` double default null comment '-',
    `ASSET_IMPAIRMENT_INCOME_YOY` double default null comment '(环比%)',
    `OTHERRIGHT_FAIRVALUE_CHANGE` double default null comment '-',
    `OTHERRIGHT_FAIRVALUE_CHANGE_YOY` double default null comment '(环比%)',
    `CREDIT_IMPAIRMENT_LOSS_QOQ` double default null comment '-',
    `SETUP_PROFIT_CHANGE_QOQ` double default null comment '-',
    `ASSET_IMPAIRMENT_LOSS` double default null comment '-',
    `ASSET_IMPAIRMENT_LOSS_YOY` double default null comment '(环比%)',
    `OPERATE_INCOME_OTHER_QOQ` double default null comment '-',
    `NETPROFIT_OTHER_QOQ` double default null comment '-',
    `OPERATE_INCOME` double default null comment '-',
    `OPERATE_INCOME_YOY` double default null comment '(环比%)',
    `COMMISSION_NI_OTHER_QOQ` double default null comment '-',
    `OTHER_INCOME` double default null comment '-',
    `OTHER_INCOME_YOY` double default null comment '(环比%)',
    `CREDITOR_IMPAIRMENT_RESERVE` double default null comment '-',
    `CREDITOR_IMPAIRMENT_RESERVE_YOY` double default null comment '(环比%)',
    `OTHER_BUSINESS_INCOME_QOQ` double default null comment '-',
    `OPERATE_PROFIT_QOQ` double default null comment '-',
    `PARENT_OCI_BALANCE_QOQ` double default null comment '-',
    `UNABLE_OCI_OTHER_QOQ` double default null comment '-',
    `FINANCE_EXPENSE` double default null comment '-',
    `FINANCE_EXPENSE_YOY` double default null comment '(环比%)',
    `BROKER_NI` double default null comment '-',
    `BROKER_NI_YOY` double default null comment '(环比%)',
    `NONCURRENT_DISPOSAL_INCOME` double default null comment '-',
    `NONCURRENT_DISPOSAL_INCOME_YOY` double default null comment '(环比%)',
    `ME_RESEARCH_EXPENSE_QOQ` double default null comment '-',
    `REINSURE_INCOME` double default null comment '-',
    `REINSURE_INCOME_YOY` double default null comment '(环比%)',
    `INCOME_TAX_QOQ` double default null comment '-',
    `PRECOMBINE_PROFIT_QOQ` double default null comment '-',
    `TOTAL_OPERATE_COST_QOQ` double default null comment '-',
    `NETPROFIT_BALANCE_QOQ` double default null comment '-',
    `NONBUSINESS_INCOME_QOQ` double default null comment '-',
    `DEDUCT_PARENT_NETPROFIT_QOQ` double default null comment '-',
    `NET_COMPENSATE_EXPENSE_QOQ` double default null comment '-',
    `REINSURE_EXPENSE` double default null comment '-',
    `REINSURE_EXPENSE_YOY` double default null comment '(环比%)',
    `BROKER_FEE_NI` double default null comment '-',
    `BROKER_FEE_NI_YOY` double default null comment '(环比%)',
    `COMPENSATE_EXPENSE` double default null comment '-',
    `COMPENSATE_EXPENSE_YOY` double default null comment '(环比%)',
    `TOTAL_PROFIT` double default null comment '-',
    `TOTAL_PROFIT_YOY` double default null comment '(环比%)',
    `CASHFLOW_HEDGE_VALID_QOQ` double default null comment '-',
    `CREDIT_IMPAIRMENT_INCOME_QOQ` double default null comment '-',
    `OPERATE_EXPENSE` double default null comment '-',
    `OPERATE_EXPENSE_YOY` double default null comment '(环比%)',
    `OCI_OTHER` double default null comment '-',
    `OCI_OTHER_YOY` double default null comment '(环比%)',
    `TOTAL_OPERATE_INCOME` double default null comment '-',
    `TOTAL_OPERATE_INCOME_YOY` double default null comment '(环比%)',
    `SALE_EXPENSE` double default null comment '-',
    `SALE_EXPENSE_YOY` double default null comment '(环比%)',
    `ASSET_IMPAIRMENT_LOSS_QOQ` double default null comment '-',
    `RIGHTLAW_UNABLE_OCI_QOQ` double default null comment '-',
    `CREDIT_IMPAIRMENT_INCOME` double default null comment '-',
    `CREDIT_IMPAIRMENT_INCOME_YOY` double default null comment '(环比%)',
    `NONBUSINESS_INCOME` double default null comment '-',
    `NONBUSINESS_INCOME_YOY` double default null comment '(环比%)',
    `RESEARCH_EXPENSE_QOQ` double default null comment '-',
    `PARENT_NETPROFIT_QOQ` double default null comment '-',
    `FUND_SALE_NI_QOQ` double default null comment '-',
    `INTEREST_INCOME_QOQ` double default null comment '-',
    `FEE_COMMISSION_INCOME_QOQ` double default null comment '-',
    `POLICY_BONUS_EXPENSE` double default null comment '-',
    `POLICY_BONUS_EXPENSE_YOY` double default null comment '(环比%)',
    `FE_INTEREST_INCOME` double default null comment '-',
    `FE_INTEREST_INCOME_YOY` double default null comment '(环比%)',
    `REPORT_DATE` double default null comment '-',
    `UPDATE_DATE` double default null comment '-',
    `OPERATE_EXPENSE_OTHER` double default null comment '-',
    `OPERATE_EXPENSE_OTHER_YOY` double default null comment '(环比%)',
    `ACF_END_INCOME` double default null comment '-',
    `ACF_END_INCOME_YOY` double default null comment '(环比%)',
    `BROKER_NI_QOQ` double default null comment '-',
    `BANK_INTEREST_INCOME_QOQ` double default null comment '-',
    `PARENT_OCI` double default null comment '-',
    `PARENT_OCI_YOY` double default null comment '(环比%)',
    `OTHER_COMPRE_INCOME_QOQ` double default null comment '-',
    `CREDITRISK_FAIRVALUE_CHANGE` double default null comment '-',
    `CREDITRISK_FAIRVALUE_CHANGE_YOY` double default null comment '(环比%)',
    `REINSURE_PREMIUM_QOQ` double default null comment '-',
    `INTEREST_EXPENSE` double default null comment '-',
    `INTEREST_EXPENSE_YOY` double default null comment '(环比%)',
    `ABLE_OCI_OTHER` double default null comment '-',
    `ABLE_OCI_OTHER_YOY` double default null comment '(环比%)',
    `COMPENSATE_EXPENSE_QOQ` double default null comment '-',
    `SURRENDER_VALUE_QOQ` double default null comment '-',
    `FINANCE_ADVISER_NI_QOQ` double default null comment '-',
    `TCI_OTHER` double default null comment '-',
    `TCI_OTHER_YOY` double default null comment '(环比%)',
    `ME_RESEARCH_EXPENSE` double default null comment '-',
    `ME_RESEARCH_EXPENSE_YOY` double default null comment '(环比%)',
    `OTHER_INCOME_QOQ` double default null comment '-',
    `OPERATE_PROFIT` double default null comment '-',
    `OPERATE_PROFIT_YOY` double default null comment '(环比%)',
    `EARNED_PREMIUM` double default null comment '-',
    `EARNED_PREMIUM_YOY` double default null comment '(环比%)',
    `TOTAL_PROFIT_QOQ` double default null comment '-',
    `UNCONFIRM_INVEST_LOSS_QOQ` double default null comment '-',
    `EFFECT_TP_OTHER_QOQ` double default null comment '-',
    `DISCONTINUED_NETPROFIT_QOQ` double default null comment '-',
    `CREDITOR_FAIRVALUE_CHANGE_QOQ` double default null comment '-',
    `REINSURE_EXPENSE_QOQ` double default null comment '-',
    `FEE_COMMISSION_NI_QOQ` double default null comment '-',
    `CASHFLOW_HEDGE_VALID` double default null comment '-',
    `CASHFLOW_HEDGE_VALID_YOY` double default null comment '(环比%)',
    `FINANCE_ADVISER_NI` double default null comment '-',
    `FINANCE_ADVISER_NI_YOY` double default null comment '(环比%)',
    `AMORTIZE_INSURANCE_RESERVE` double default null comment '-',
    `AMORTIZE_INSURANCE_RESERVE_YOY` double default null comment '(环比%)',
    `MINORITY_TCI_QOQ` double default null comment '-',
    `EFFECT_NETPROFIT_BALANCE_QOQ` double default null comment '-',
    `ABLE_OCI` double default null comment '-',
    `ABLE_OCI_YOY` double default null comment '(环比%)',
    `CONVERT_DIFF` double default null comment '-',
    `CONVERT_DIFF_YOY` double default null comment '(环比%)',
    `TOTAL_OPERATE_INCOME_QOQ` double default null comment '-',
    `CONTINUED_NETPROFIT_QOQ` double default null comment '-',
    `NET_COMPENSATE_EXPENSE` double default null comment '-',
    `NET_COMPENSATE_EXPENSE_YOY` double default null comment '(环比%)',
    `OPERATE_EXPENSE_BALANCE` double default null comment '-',
    `OPERATE_EXPENSE_BALANCE_YOY` double default null comment '(环比%)',
    `SURRENDER_VALUE` double default null comment '-',
    `SURRENDER_VALUE_YOY` double default null comment '(环比%)',
    `EFFECT_NETPROFIT_OTHER_QOQ` double default null comment '-',
    `CREDITRISK_FAIRVALUE_CHANGE_QOQ` double default null comment '-',
    `TOI_OTHER` double default null comment '-',
    `TOI_OTHER_YOY` double default null comment '(环比%)',
    `NONCURRENT_DISPOSAL_LOSS` double default null comment '-',
    `NONCURRENT_DISPOSAL_LOSS_YOY` double default null comment '(环比%)',
    `RESEARCH_EXPENSE` double default null comment '-',
    `RESEARCH_EXPENSE_YOY` double default null comment '(环比%)',
    `UNINSURANCE_CI_QOQ` double default null comment '-',
    `INVEST_INCOME` double default null comment '-',
    `INVEST_INCOME_YOY` double default null comment '(环比%)',
    `TOTAL_PROFIT_BALANCE` double default null comment '-',
    `TOTAL_PROFIT_BALANCE_YOY` double default null comment '(环比%)',
    `EXTRACT_INSURANCE_RESERVE_QOQ` double default null comment '-',
    `HMI_AFA_QOQ` double default null comment '-',
    `FINANCE_EXPENSE_QOQ` double default null comment '-',
    `PARENT_OCI_OTHER` double default null comment '-',
    `PARENT_OCI_OTHER_YOY` double default null comment '(环比%)',
    `RECOMMEND_NI_QOQ` double default null comment '-',
    `BASIC_EPS` double default null comment '-',
    `BASIC_EPS_YOY` double default null comment '(环比%)',
    `OPERATE_TAX_ADD_QOQ` double default null comment '-',
    `AFA_FAIRVALUE_CHANGE_QOQ` double default null comment '-',
    `OPERATE_EXPENSE_OTHER_QOQ` double default null comment '-',
    `ABLE_OCI_QOQ` double default null comment '-',
    `HMI_AFA` double default null comment '-',
    `HMI_AFA_YOY` double default null comment '(环比%)',
    `OPERATE_INCOME_OTHER` double default null comment '-',
    `OPERATE_INCOME_OTHER_YOY` double default null comment '(环比%)',
    `SALE_EXPENSE_QOQ` double default null comment '-',
    `FUND_SALE_NI` double default null comment '-',
    `FUND_SALE_NI_YOY` double default null comment '(环比%)',
    `AMORTIZE_REINSURE_EXPENSE` double default null comment '-',
    `AMORTIZE_REINSURE_EXPENSE_YOY` double default null comment '(环比%)',
    `CONTINUED_NETPROFIT` double default null comment '-',
    `CONTINUED_NETPROFIT_YOY` double default null comment '(环比%)',
    `EFFECT_NETPROFIT_OTHER` double default null comment '-',
    `EFFECT_NETPROFIT_OTHER_YOY` double default null comment '(环比%)',
    `UNINSURANCE_CNI` double default null comment '-',
    `UNINSURANCE_CNI_YOY` double default null comment '(环比%)',
    `BANK_INTEREST_INCOME` double default null comment '-',
    `BANK_INTEREST_INCOME_YOY` double default null comment '(环比%)',
    `AMORTIZE_REINSURE_EXPENSE_QOQ` double default null comment '-',
    `DEDUCT_PARENT_NETPROFIT` double default null comment '-',
    `DEDUCT_PARENT_NETPROFIT_YOY` double default null comment '(环比%)',
    `INVEST_INCOME_QOQ` double default null comment '-',
    `OPERATE_PROFIT_OTHER_QOQ` double default null comment '-',
    `RIGHTLAW_ABLE_OCI_QOQ` double default null comment '-',
    `ASSET_DISPOSAL_INCOME` double default null comment '-',
    `ASSET_DISPOSAL_INCOME_YOY` double default null comment '(环比%)',
    `NET_CONTRACT_RESERVE_QOQ` double default null comment '-',
    `AFA_FAIRVALUE_CHANGE` double default null comment '-',
    `AFA_FAIRVALUE_CHANGE_YOY` double default null comment '(环比%)',
    `EFFECT_TCI_BALANCE_QOQ` double default null comment '-',
    `EARNED_PREMIUM_BALANCE_QOQ` double default null comment '-',
    `SECURITY_NAME_ABBR` double default null comment '-',
    `INTEREST_EXPENSE_QOQ` double default null comment '-',
    `BASIC_EPS_QOQ` double default null comment '-',
    `SECURITY_TYPE_CODE` double default null comment '-',
    `UNINSURANCE_CI` double default null comment '-',
    `UNINSURANCE_CI_YOY` double default null comment '(环比%)',
    `PARENT_TCI` double default null comment '-',
    `PARENT_TCI_YOY` double default null comment '(环比%)',
    `PARENT_TCI_QOQ` double default null comment '-',
    `INTEREST_INCOME` double default null comment '-',
    `INTEREST_INCOME_YOY` double default null comment '(环比%)',
    `NET_EXPOSURE_INCOME` double default null comment '-',
    `NET_EXPOSURE_INCOME_YOY` double default null comment '(环比%)',
    `OCI_OTHER_QOQ` double default null comment '-',
    `UNINSURANCE_CE` double default null comment '-',
    `UNINSURANCE_CE_YOY` double default null comment '(环比%)',
    `OPERATE_INCOME_BALANCE` double default null comment '-',
    `OPERATE_INCOME_BALANCE_YOY` double default null comment '(环比%)',
    `INCOME_TAX` double default null comment '-',
    `INCOME_TAX_YOY` double default null comment '(环比%)',
    `INVEST_JOINT_INCOME` double default null comment '-',
    `INVEST_JOINT_INCOME_YOY` double default null comment '(环比%)',
    `MINORITY_OCI_QOQ` double default null comment '-',
    `FE_INTEREST_INCOME_QOQ` double default null comment '-',
    `TOC_OTHER` double default null comment '-',
    `TOC_OTHER_YOY` double default null comment '(环比%)',
    `TOC_OTHER_QOQ` double default null comment '-',
    `DILUTED_EPS` double default null comment '-',
    `DILUTED_EPS_YOY` double default null comment '(环比%)',
    `PARENT_OCI_BALANCE` double default null comment '-',
    `PARENT_OCI_BALANCE_YOY` double default null comment '(环比%)',
    `ASSETMANAGE_FEE_NI` double default null comment '-',
    `ASSETMANAGE_FEE_NI_YOY` double default null comment '(环比%)',
    `MINORITY_OCI` double default null comment '-',
    `MINORITY_OCI_YOY` double default null comment '(环比%)',
    `TCI_BALANCE` double default null comment '-',
    `TCI_BALANCE_YOY` double default null comment '(环比%)',
    `UNABLE_OCI_QOQ` double default null comment '-',
    `CURRENCY` double default null comment '-',
    `INVESTBANK_FEE_NI` double default null comment '-',
    `INVESTBANK_FEE_NI_YOY` double default null comment '(环比%)',
    `REPORT_DATE_NAME` double default null comment '-',
    `OTHERRIGHT_FAIRVALUE_CHANGE_QOQ` double default null comment '-',
    `SECURITY_UNDERWRITE_NI` double default null comment '-',
    `SECURITY_UNDERWRITE_NI_YOY` double default null comment '(环比%)',
    `PRECOMBINE_TCI_QOQ` double default null comment '-',
    `NET_EXPOSURE_INCOME_QOQ` double default null comment '-',
    `NOTICE_DATE` double default null comment '-',
    `EXCHANGE_INCOME_QOQ` double default null comment '-',
    `MINORITY_INTEREST` double default null comment '-',
    `MINORITY_INTEREST_YOY` double default null comment '(环比%)',
    `CONVERT_DIFF_QOQ` double default null comment '-',
    `UNINSURANCE_CE_QOQ` double default null comment '-',
    `EARNED_PREMIUM_QOQ` double default null comment '-',
    `OPERATE_COST_QOQ` double default null comment '-',
    `TOTAL_COMPRE_INCOME_QOQ` double default null comment '-',
    `SECURITY_UNDERWRITE_NI_QOQ` double default null comment '-',
    `AMORTIZE_INSURANCE_RESERVE_QOQ` double default null comment '-',
    `ASSET_DISPOSAL_INCOME_QOQ` double default null comment '-',
    `INSURANCE_INCOME` double default null comment '-',
    `INSURANCE_INCOME_YOY` double default null comment '(环比%)',
    `TOTAL_PROFIT_BALANCE_QOQ` double default null comment '-',
    `INSURANCE_INCOME_QOQ` double default null comment '-',
    `FAIRVALUE_CHANGE_QOQ` double default null comment '-',
    `FUND_MANAGE_NI` double default null comment '-',
    `FUND_MANAGE_NI_YOY` double default null comment '(环比%)',
    `INTEREST_NI_QOQ` double default null comment '-',
    `TCI_OTHER_QOQ` double default null comment '-',
    `OPERATE_INCOME_QOQ` double default null comment '-',
    `FEE_COMMISSION_EXPENSE_QOQ` double default null comment '-',
    `BANK_INTEREST_EXPENSE_QOQ` double default null comment '-',

    Process finished with exit code 0

        primary key (`id`) using btree',
    key `inv_finance_lr_index` (`security_code`',`report_type`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-利润';