/*
财务分析-资产负债-证劵类-报告期表
*/

drop table if exists `inv_finance_zcfz_securities_period`;
create table `inv_finance_zcfz_securities_period` (
  `id` bigint not null auto_increment comment 'id',
  `security_code` varchar(10) character set utf8 collate utf8_bin not null comment '股票代码',
-- companytype=1
  `report_date` datetime default null comment '报告日期',
-- 资产
  `monetaryfunds` double default null comment '货币资金',
  `monetaryfunds_yoy` double default null comment '货币资金(环比%)',
  `customer_deposit` double default null comment '客户资金存款',
  `customer_deposit_yoy` double default null comment '客户资金存款(环比%)',
  `settle_excess_reserve` double default null comment '结算备付金',
  `settle_excess_reserve_yoy` double default null comment '结算备付金(环比%)',
  `customer_excess_reserve` double default null comment '客户备付金',
  `customer_excess_reserve_yoy` double default null comment '客户备付金(环比%)',
  `fin_fund` double default null comment '融出资金',
  `fin_fund_yoy` double default null comment '融出资金(环比%)',
  `derive_finasset` double default null comment '衍生金融资产',
  `derive_finasset_yoy` double default null comment '衍生金融资产(环比%)',
  `buy_resale_finasset` double default null comment '买入返售金融资产',
  `buy_resale_finasset_yoy` double default null comment '买入返售金融资产(环比%)',
  `receivables` double default null comment '应收款项',
  `receivables_yoy` double default null comment '应收款项(环比%)',
  `refund_deposit_pay` double default null comment '存出保证金',
  `refund_deposit_pay_yoy` double default null comment '存出保证金(环比%)',
  `trade_finasset_notfvtpl` double default null comment '交易性金融资产',
  `trade_finasset_notfvtpl_yoy` double default null comment '交易性金融资产(环比%)',
  `creditor_invest` double default null comment '债权投资',
  `creditor_invest_yoy` double default null comment '债权投资(环比%)',
  `other_equity_invest` double default null comment '其他权益工具投资',
  `other_equity_invest_yoy` double default null comment '其他权益工具投资(环比%)',
  `long_equity_invest` double default null comment '长期股权投资',
  `long_equity_invest_yoy` double default null comment '长期股权投资(环比%)',
  `invest_realestate` double default null comment '投资性房地产',
  `invest_realestate_yoy` double default null comment '投资性房地产(环比%)',
  `fixed_asset` double default null comment '固定资产',
  `fixed_asset_yoy` double default null comment '固定资产(环比%)',
  `useright_asset` double default null comment '使用权资产',
  `useright_asset_yoy` double default null comment '使用权资产(环比%)',
  `intangible_asset` double default null comment '无形资产',
  `intangible_asset_yoy` double default null comment '无形资产(环比%)',
  `goodwill` double default null comment '商誉',
  `goodwill_yoy` double default null comment '商誉(环比%)',
  `defer_tax_asset` double default null comment '递延所得税资产',
  `defer_tax_asset_yoy` double default null comment '递延所得税资产(环比%)',
  `other_asset` double default null comment '其他资产',
  `other_asset_yoy` double default null comment '其他资产(环比%)',
  `total_assets` double default null comment '资产总计',
  `total_assets_yoy` double default null comment '资产总计(环比%)',
-- 负债
  `short_fin_payable` double default null comment '应付短期融资款',
  `short_fin_payable_yoy` double default null comment '应付短期融资款(环比%)',
  `borrow_fund` double default null comment '拆入资金',
  `borrow_fund_yoy` double default null comment '拆入资金(环比%)',
  `trade_finliab_notfvtpl` double default null comment '交易性金融负债',
  `trade_finliab_notfvtpl_yoy` double default null comment '交易性金融负债(环比%)',
  `derive_finliab` double default null comment '衍生金融负债',
  `derive_finliab_yoy` double default null comment '衍生金融负债(环比%)',
  `sell_repo_finasset` double default null comment '卖出回购金融资产款',
  `sell_repo_finasset_yoy` double default null comment '卖出回购金融资产款(环比%)',
  `agent_trade_security` double default null comment '代理买卖证券款',
  `agent_trade_security_yoy` double default null comment '代理买卖证券款(环比%)',
  `agent_underwrite_security` double default null comment '代理承销证券款',
  `agent_underwrite_security_yoy` double default null comment '代理承销证券款(环比%)',
  `accounts_payable` double default null comment '应付账款',
  `accounts_payable_yoy` double default null comment '应付账款(环比%)',
  `staff_salary_payable` double default null comment '应付职工薪酬',
  `staff_salary_payable_yoy` double default null comment '应付职工薪酬(环比%)',
  `tax_payable` double default null comment '应交税费',
  `tax_payable_yoy` double default null comment '应交税费(环比%)',
  `predict_liab` double default null comment '预计负债',
  `predict_liab_yoy` double default null comment '预计负债(环比%)',
  `bond_payable` double default null comment '应付债券',
  `bond_payable_yoy` double default null comment '应付债券(环比%)',
  `lease_liab` double default null comment '租赁负债',
  `lease_liab_yoy` double default null comment '租赁负债(环比%)',
  `defer_tax_liab` double default null comment '递延所得税负债',
  `defer_tax_liab_yoy` double default null comment '递延所得税负债(环比%)',
  `other_liab` double default null comment '其他负债',
  `other_liab_yoy` double default null comment '其他负债(环比%)',
  `liab_other` double default null comment '负债其他项目',
  `liab_other_yoy` double default null comment '负债其他项目(环比%)',
  `total_liabilities` double default null comment '负债合计',
  `total_liabilities_yoy` double default null comment '负债合计(环比%)',

-- 所有者权益(或股东权益)
  `share_capital` double default null comment '股本',
  `share_capital_yoy` double default null comment '股本(环比%)',
  `capital_reserve` double default null comment '资本公积',
  `capital_reserve_yoy` double default null comment '资本公积(环比%)',
  `other_compre_income` double default null comment '其他综合收益',
  `other_compre_income_yoy` double default null comment '其他综合收益(环比%)',
  `surplus_reserve` double default null comment '盈余公积',
  `surplus_reserve_yoy` double default null comment '盈余公积(环比%)',
  `general_risk_reserve` double default null comment '一般风险准备',
  `general_risk_reserve_yoy` double default null comment '一般风险准备(环比%)',
  `unassign_rpofit` double default null comment '未分配利润',
  `unassign_rpofit_yoy` double default null comment '未分配利润(环比%)',
  `total_parent_equity` double default null comment '归属于母公司股东权益总计',
  `total_parent_equity_yoy` double default null comment '归属于母公司股东权益总计(环比%)',
  `minority_equity` double default null comment '少数股东权益',
  `minority_equity_yoy` double default null comment '少数股东权益(环比%)',
  `total_equity` double default null comment '股东权益合计',
  `total_equity_yoy` double default null comment '股东权益合计(环比%)',
  `total_liab_equity` double default null comment '负债和股东权益总计',
  `total_liab_equity_yoy` double default null comment '负债和股东权益总计(环比%)',
  `opinion_type` varchar(20) character set utf8 collate utf8_bin comment '审计意见(境内)',

  primary key (`id`) using btree,
  unique key `employee_name` (`security_code`,`report_date`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-资产负债-证劵类-报告期表';
