/*
财务分析-资产负债-保险类-报告期表
*/

drop table if exists `inv_finance_zcfz_insurance_period`;
create table `inv_finance_zcfz_insurance_period` (
  `id` bigint not null auto_increment comment 'id',
  `security_code` varchar(10) character set utf8 collate utf8_bin not null comment '股票代码',
-- companytype=2

  `report_date` datetime default null comment '报告日期',
-- 资产
  `monetaryfunds` double default null comment '货币资金',
  `monetaryfunds_yoy` double default null comment '货币资金(环比%)',
  `fvtpl_finasset` double default null comment '以公允价值计量且其变动计入当期损益的金融资产',
  `fvtpl_finasset_yoy` double default null comment '以公允价值计量且其变动计入当期损益的金融资产(环比%)',
  `buy_resale_finasset` double default null comment '买入返售金融资产',
  `buy_resale_finasset_yoy` double default null comment '买入返售金融资产(环比%)',
  `interest_rece` double default null comment '应收利息',
  `interest_rece_yoy` double default null comment '应收利息(环比%)',
  `premium_rece` double default null comment '应收保费',
  `premium_rece_yoy` double default null comment '应收保费(环比%)',
  `reinsure_rece` double default null comment '应收分保账款',
  `reinsure_rece_yoy` double default null comment '应收分保账款(环比%)',
  `rud_reserve_rece` double default null comment '应收分保未到期责任准备金',
  `rud_reserve_rece_yoy` double default null comment '应收分保未到期责任准备金(环比%)',
  `ruc_reserve_rece` double default null comment '应收分保未决赔偿准备金',
  `ruc_reserve_rece_yoy` double default null comment '应收分保未决赔偿准备金(环比%)',
  `loan_advance` double default null comment '发放贷款及垫款',
  `loan_advance_yoy` double default null comment '发放贷款及垫款(环比%)',
  `trade_finasset_notfvtpl` double default null comment '交易性金融资产',
  `trade_finasset_notfvtpl_yoy` double default null comment '交易性金融资产(环比%)',
  `other_rece` double default null comment '其他应收款',
  `other_rece_yoy` double default null comment '其他应收款(环比%)',
  `time_deposit` double default null comment '定期存款',
  `time_deposit_yoy` double default null comment '定期存款(环比%)',
  `available_sale_finasset` double default null comment '可供出售金融资产',
  `available_sale_finasset_yoy` double default null comment '可供出售金融资产(环比%)',
  `hold_maturity_invest` double default null comment '持有至到期投资',
  `hold_maturity_invest_yoy` double default null comment '持有至到期投资(环比%)',
  `accounts_rece` double default null comment '应收账款',
  `accounts_rece_yoy` double default null comment '应收账款(环比%)',
  `long_equity_invest` double default null comment '长期股权投资',
  `long_equity_invest_yoy` double default null comment '长期股权投资(环比%)',
  `refund_capital_deposit` double default null comment '存出资本保证金',
  `refund_capital_deposit_yoy` double default null comment '存出资本保证金(环比%)',
  `invest_realestate` double default null comment '投资性房地产',
  `invest_realestate_yoy` double default null comment '投资性房地产(环比%)',
  `fixed_asset` double default null comment '固定资产',
  `fixed_asset_yoy` double default null comment '固定资产(环比%)',
  `cip` double default null comment '在建工程',
  `cip_yoy` double default null comment '在建工程(环比%)',
  `useright_asset` double default null comment '使用权资产',
  `useright_asset_yoy` double default null comment '使用权资产(环比%)',
  `intangible_asset` double default null comment '无形资产',
  `intangible_asset_yoy` double default null comment '无形资产(环比%)',
  `goodwill` double default null comment '商誉',
  `goodwill_yoy` double default null comment '商誉(环比%)',
  `defer_tax_asset` double default null comment '递延所得税资产',
  `defer_tax_asset_yoy` double default null comment '递延所得税资产(环比%)',
  `asset_other` double default null comment '资产其他项目',
  `asset_other_yoy` double default null comment '资产其他项目(环比%)',
  `total_assets` double default null comment '资产总计',
  `total_assets_yoy` double default null comment '资产总计(环比%)',

  `sell_repo_finasset` double default null comment '卖出回购金融资产款',
  `sell_repo_finasset_yoy` double default null comment '卖出回购金融资产款(环比%)',
  `accounts_payable` double default null comment '应付账款',
  `accounts_payable_yoy` double default null comment '应付账款(环比%)',
  `advance_rece` double default null comment '预收账款',
  `advance_rece_yoy` double default null comment '预收账款(环比%)',
  `advance_premium` double default null comment '预收保费',
  `advance_premium_yoy` double default null comment '预收保费(环比%)',
  `fee_commission_payable` double default null comment '应付手续费及佣金',
  `fee_commission_payable_yoy` double default null comment '应付手续费及佣金(环比%)',
  `reinsure_payable` double default null comment '应付分保账款',
  `reinsure_payable_yoy` double default null comment '应付分保账款(环比%)',
  `staff_salary_payable` double default null comment '应付职工薪酬',
  `staff_salary_payable_yoy` double default null comment '应付职工薪酬(环比%)',
  `tax_payable` double default null comment '应交税费',
  `tax_payable_yoy` double default null comment '应交税费(环比%)',
  `interest_payable` double default null comment '应付利息',
  `interest_payable_yoy` double default null comment '应付利息(环比%)',
  `compensate_payable` double default null comment '应付赔付款',
  `compensate_payable_yoy` double default null comment '应付赔付款(环比%)',
  `long_loan` double default null comment '长期借款',
  `long_loan_yoy` double default null comment '长期借款(环比%)',
  `bond_payable` double default null comment '应付债券',
  `bond_payable_yoy` double default null comment '应付债券(环比%)',
  `lease_liab` double default null comment '租赁负债',
  `lease_liab_yoy` double default null comment '租赁负债(环比%)',
  `defer_tax_liab` double default null comment '递延所得税负债',
  `defer_tax_liab_yoy` double default null comment '递延所得税负债(环比%)',
  `liab_other` double default null comment '负债其他项目',
  `liab_other_yoy` double default null comment '负债其他项目(环比%)',
  `total_liabilities` double default null comment '负债合计',
  `total_liabilities_yoy` double default null comment '负债合计(环比%)',

  `share_capital` double default null comment '股本',
  `share_capital_yoy` double default null comment '股本(环比%)',
  `capital_reserve` double default null comment '资本公积',
  `capital_reserve_yoy` double default null comment '资本公积(环比%)',
  `other_compre_income` double default null comment '其他综合收益',
  `other_compre_income_yoy` double default null comment '其他综合收益(环比%)',
  `surplus_reserve` double default null comment '盈余公积',
  `surplus_reserve_yoy` double default null comment '盈余公积(环比%)',
  `unassign_rpofit` double default null comment '未分配利润',
  `unassign_rpofit_yoy` double default null comment '未分配利润(环比%)',
  `total_parent_equity` double default null comment '归属于母公司股东权益总计',
  `total_parent_equity_yoy` double default null comment '归属于母公司股东权益总计(环比%)',
  `minority_equity` double default null comment '少数股东权益',
  `minority_equity_yoy` double default null comment '少数股东权益(环比%)',
  `total_equity` double default null comment '股东权益合计',
  `total_equity_yoy` double default null comment '股东权益合计(环比%)',
  `total_liab_equity` double default null comment '负债和股东权益总计',
  `total_liab_equity_yoy` double default null comment '负债和股东权益总计(环比%)',
  `opinion_type` varchar(20) character set utf8 collate utf8_bin comment '审计意见(境内)',

  primary key (`id`) using btree,
  unique key `employee_name` (`security_code`,`report_date`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-资产负债-保险类-报告期表';
