/*
财务分析-资产负债-银行类-报告期表
*/

drop table if exists `inv_finance_zcfz_bank_period`;
create table `inv_finance_zcfz_bank_period` (
  `id` bigint not null auto_increment comment 'id',
  `security_code` varchar(10) character set utf8 collate utf8_bin not null comment '股票代码',
-- companytype=3

  `report_date` datetime default null comment '报告日期',
-- 资产
  `cash_deposit_pbc` double default null comment '现金及存放中央银行款项',
  `cash_deposit_pbc_yoy` double default null comment '现金及存放中央银行款项(环比%)',
  `deposit_interbank` double default null comment '存放同业款项',
  `deposit_interbank_yoy` double default null comment '存放同业款项(环比%)',
  `precious_metal` double default null comment '贵金属',
  `precious_metal_yoy` double default null comment '贵金属(环比%)',
  `lend_fund` double default null comment '拆出资金',
  `lend_fund_yoy` double default null comment '拆出资金(环比%)',
  `fvtpl_finasset` double default null comment '以公允价值计量且其变动计入当期损益的金融资产',
  `fvtpl_finasset_yoy` double default null comment '以公允价值计量且其变动计入当期损益的金融资产(环比%)',
  `derive_finasset` double default null comment '衍生金融资产',
  `derive_finasset_yoy` double default null comment '衍生金融资产(环比%)',
  `buy_resale_finasset` double default null comment '买入返售金融资产',
  `buy_resale_finasset_yoy` double default null comment '买入返售金融资产(环比%)',
  `loan_advance` double default null comment '发放贷款及垫款',
  `loan_advance_yoy` double default null comment '发放贷款及垫款(环比%)',
  `amortize_cost_finasset` double default null comment '以摊余成本计量的金融资产',
  `amortize_cost_finassetyoy` double default null comment '以摊余成本计量的金融资产(环比%)',
  `fvtoci_finasset` double default null comment '以公允价值计量且其变动计入其他综合收益的金融资产',
  `fvtoci_finasset_yoy` double default null comment '以公允价值计量且其变动计入其他综合收益的金融资产(环比%)',
  `long_equity_invest` double default null comment '长期股权投资',
  `long_equity_invest_yoy` double default null comment '长期股权投资(环比%)',
  `fixed_asset` double default null comment '固定资产',
  `fixed_asset_yoy` double default null comment '固定资产(环比%)',
  `intangible_asset` double default null comment '无形资产',
  `intangible_asset_yoy` double default null comment '无形资产(环比%)',
  `goodwill` double default null comment '商誉',
  `goodwill_yoy` double default null comment '商誉(环比%)',
  `defer_tax_asset` double default null comment '递延所得税资产',
  `defer_tax_asset_yoy` double default null comment '递延所得税资产(环比%)',
  `other_asset` double default null comment '其他资产',
  `other_asset_yoy` double default null comment '其他资产(环比%)',
  `asset_other` double default null comment '资产其他项目',
  `asset_other_yoy` double default null comment '资产其他项目(环比%)',
  `total_assets` double default null comment '资产总计',
  `total_assets_yoy` double default null comment '资产总计(环比%)',

  `loan_pbc` double default null comment '向中央银行借款',
  `loan_pbc_yoy` double default null comment '向中央银行借款(环比%)',
  `iofi_deposit` double default null comment '同业及其他金融机构存放款项',
  `iofi_deposit_yoy` double default null comment '同业及其他金融机构存放款项(环比%)',
  `borrow_fund` double default null comment '拆入资金',
  `borrow_fund_yoy` double default null comment '拆入资金(环比%)',
  `fvtpl_finliab` double default null comment '以公允价值计量且其变动计入当期损益的金融负债',
  `fvtpl_finliab_yoy` double default null comment '以公允价值计量且其变动计入当期损益的金融负债(环比%)',
  `derive_finliab` double default null comment '衍生金融负债',
  `derive_finliab_yoy` double default null comment '衍生金融负债(环比%)',
  `sell_repo_finasset` double default null comment '卖出回购金融资产款',
  `sell_repo_finasset_yoy` double default null comment '卖出回购金融资产款(环比%)',
  `accept_deposit` double default null comment '吸收存款',
  `accept_deposit_yoy` double default null comment '吸收存款(环比%)',
  `staff_salary_payable` double default null comment '应付职工薪酬',
  `staff_salary_payable_yoy` double default null comment '应付职工薪酬(环比%)',
  `tax_payable` double default null comment '应交税费',
  `tax_payable_yoy` double default null comment '应交税费(环比%)',
  `predict_liab` double default null comment '预计负债',
  `predict_liab_yoy` double default null comment '预计负债(环比%)',
  `defer_tax_liab` double default null comment '递延所得税负债',
  `defer_tax_liab_yoy` double default null comment '递延所得税负债(环比%)',
  `bond_payable` double default null comment '应付债券',
  `bond_payable_yoy` double default null comment '应付债券(环比%)',
  `other_liab` double default null comment '其他负债',
  `other_liab_yoy` double default null comment '其他负债(环比%)',
  `total_liabilities` double default null comment '负债合计',
  `total_liabilities_yoy` double default null comment '负债合计(环比%)',

  `share_capital` double default null comment '股本',
  `share_capital_yoy` double default null comment '股本(环比%)',
  `other_equity_other` double default null comment '其他权益工具',
  `other_equity_other_yoy` double default null comment '其他权益工具(环比%)',
  `preferred_shares` double default null comment '优先股',
  `preferred_shares_yoy` double default null comment '优先股(环比%)',
  `perpetual_bond` double default null comment '永续债',
  `perpetual_bond_yoy` double default null comment '永续债(环比%)',
  `capital_reserve` double default null comment '资本公积',
  `capital_reserve_yoy` double default null comment '资本公积(环比%)',
  `other_compre_income` double default null comment '其他综合收益',
  `other_compre_income_yoy` double default null comment '其他综合收益(环比%)',
  `surplus_reserve` double default null comment '盈余公积',
  `surplus_reserve_yoy` double default null comment '盈余公积(环比%)',
  `general_risk_reserve` double default null comment '一般风险准备',
  `general_risk_reserve_yoy` double default null comment '一般风险准备(环比%)',
  `unassign_rpofit` double default null comment '未分配利润',
  `unassign_rpofit_yoy` double default null comment '未分配利润(环比%)',
  `total_parent_equity` double default null comment '归属于母公司股东权益总计',
  `total_parent_equity_yoy` double default null comment '归属于母公司股东权益总计(环比%)',
  `minority_equity` double default null comment '少数股东权益',
  `minority_equity_yoy` double default null comment '少数股东权益(环比%)',
  `total_equity` double default null comment '股东权益合计',
  `total_equity_yoy` double default null comment '股东权益合计(环比%)',
  `total_liab_equity` double default null comment '负债和股东权益总计',
  `total_liab_equity_yoy` double default null comment '负债和股东权益总计(环比%)',
  `opinion_type` varchar(20) character set utf8 collate utf8_bin comment '审计意见(境内)',

  primary key (`id`) using btree,
  unique key `employee_name` (`security_code`,`report_date`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-资产负债-银行类-报告期表';
