/*
财务分析-资产负债-普通类-报告期表
*/

drop table if exists `inv_finance_zcfz_common_period`;
create table `inv_finance_zcfz_common_period` (
  `id` bigint not null auto_increment comment 'id',
  `security_code` varchar(10) character set utf8 collate utf8_bin not null comment '股票代码',
-- companytype=4

  `report_date` datetime default null comment '报告日期',
-- 资产
  `monetaryfunds` double default null comment '货币资金',
  `monetaryfunds_yoy` double default null comment '货币资金(环比%)',
  `derive_finasset` double default null comment '衍生金融资产',
  `derive_finasset_yoy` double default null comment '衍生金融资产(环比%)',
  `note_accounts_rece` double default null comment '应收票据及应收账款',
  `note_accounts_rece_yoy` double default null comment '应收票据及应收账款(环比%)',
  `note_rece` double default null comment '应收票据',
  `note_rece_yoy` double default null comment '应收票据(环比%)',
  `accounts_rece` double default null comment '应收账款',
  `accounts_rece_yoy` double default null comment '应收账款(环比%)',
  `finance_rece` double default null comment '应收款项融资',
  `finance_rece_yoy` double default null comment '应收款项融资(环比%)',
  `prepayment` double default null comment '预付款项',
  `prepayment_yoy` double default null comment '预付款项(环比%)',
  `total_other_rece` double default null comment '其他应收款合计',
  `total_other_rece_yoy` double default null comment '其他应收款合计(环比%)',
  `dividend_rece` double default null comment '应收股利',
  `dividend_rece_yoy` double default null comment '应收股利(环比%)',
  `inventory` double default null comment '存货',
  `inventory_yoy` double default null comment '存货(环比%)',
  `contract_asset` double default null comment '合同资产',
  `contract_asset_yoy` double default null comment '合同资产(环比%)',
  `noncurrent_asset_1year` double default null comment '一年内到期的非流动资产',
  `noncurrent_asset_1year_yoy` double default null comment '一年内到期的非流动资产(环比%)',
  `other_current_asset` double default null comment '其他流动资产',
  `other_current_asset_yoy` double default null comment '其他流动资产(环比%)',
  `total_current_assets` double default null comment '流动资产合计',
  `total_current_assets_yoy` double default null comment '流动资产合计(环比%)',
  `long_rece` double default null comment '长期应收款',
  `long_rece_yoy` double default null comment '长期应收款(环比%)',
  `long_equity_invest` double default null comment '长期股权投资',
  `long_equity_invest_yoy` double default null comment '长期股权投资(环比%)',
  `other_equity_invest` double default null comment '其他权益工具投资',
  `other_equity_invest_yoy` double default null comment '其他权益工具投资(环比%)',
  `invest_realestate` double default null comment '投资性房地产',
  `invest_realestate_yoy` double default null comment '投资性房地产(环比%)',
  `fixed_asset` double default null comment '固定资产',
  `fixed_asset_yoy` double default null comment '固定资产(环比%)',
  `cip` double default null comment '在建工程',
  `cip_yoy` double default null comment '在建工程(环比%)',
  `useright_asset` double default null comment '使用权资产',
  `useright_asset_yoy` double default null comment '使用权资产(环比%)',
  `intangible_asset` double default null comment '无形资产',
  `intangible_asset_yoy` double default null comment '无形资产(环比%)',
  `develop_expense` double default null comment '开发支出',
  `develop_expense_yoy` double default null comment '开发支出(环比%)',
  `long_prepaid_expense` double default null comment '长期待摊费用',
  `long_prepaid_expense_yoy` double default null comment '长期待摊费用(环比%)',
  `defer_tax_asset` double default null comment '递延所得税资产',
  `defer_tax_asset_yoy` double default null comment '递延所得税资产(环比%)',
  `other_noncurrent_asset` double default null comment '其他非流动资产',
  `other_noncurrent_asset_yoy` double default null comment '其他非流动资产(环比%)',
  `total_noncurrent_assets` double default null comment '非流动资产合计',
  `total_noncurrent_assets_yoy` double default null comment '非流动资产合计(环比%)',
  `total_assets` double default null comment '资产总计',
  `total_assets_yoy` double default null comment '资产总计(环比%)',

  `short_loan` double default null comment '短期借款',
  `short_loan_yoy` double default null comment '短期借款(环比%)',
  `note_accounts_payable` double default null comment '应付票据及应付账款',
  `note_accounts_payable_yoy` double default null comment '应付票据及应付账款(环比%)',
  `note_payable` double default null comment '应付票据',
  `note_payable_yoy` double default null comment '应付票据(环比%)',
  `accounts_payable` double default null comment '应付账款',
  `accounts_payable_yoy` double default null comment '应付账款(环比%)',
  `contract_liab` double default null comment '合同负债',
  `contract_liab_yoy` double default null comment '合同负债(环比%)',
  `staff_salary_payable` double default null comment '应付职工薪酬',
  `staff_salary_payable_yoy` double default null comment '应付职工薪酬(环比%)',
  `tax_payable` double default null comment '应交税费',
  `tax_payable_yoy` double default null comment '应交税费(环比%)',
  `total_other_payable` double default null comment '其他应付款合计',
  `total_other_payable_yoy` double default null comment '其他应付款合计(环比%)',
  `dividend_payable` double default null comment '应付股利',
  `dividend_payable_yoy` double default null comment '应付股利(环比%)',
  `noncurrent_liab_1year` double default null comment '一年内到期的非流动负债',
  `noncurrent_liab_1year_yoy` double default null comment '一年内到期的非流动负债(环比%)',
  `other_current_liab` double default null comment '其他流动负债',
  `other_current_liab_yoy` double default null comment '其他流动负债(环比%)',
  `total_current_liab` double default null comment '流动负债合计',
  `total_current_liab_yoy` double default null comment '流动负债合计(环比%)',
  `long_loan` double default null comment '长期借款',
  `long_loan_yoy` double default null comment '长期借款(环比%)',
  `lease_liab` double default null comment '租赁负债',
  `lease_liab_yoy` double default null comment '租赁负债(环比%)',
  `long_payable` double default null comment '长期应付款',
  `long_payable_yoy` double default null comment '长期应付款(环比%)',
  `long_staffsalary_payable` double default null comment '长期应付职工薪酬',
  `long_staffsalary_payable_yoy` double default null comment '长期应付职工薪酬(环比%)',
  `predict_liab` double default null comment '预计负债',
  `predict_liab_yoy` double default null comment '预计负债(环比%)',
  `defer_income` double default null comment '递延收益',
  `defer_income_yoy` double default null comment '递延收益(环比%)',
  `defer_tax_liab` double default null comment '递延所得税负债',
  `defer_tax_liab_yoy` double default null comment '递延所得税负债(环比%)',
  `total_noncurrent_liab` double default null comment '非流动负债合计',
  `total_noncurrent_liab_yoy` double default null comment '非流动负债合计(环比%)',
  `total_liabilities` double default null comment '负债合计',
  `total_liabilities_yoy` double default null comment '负债合计(环比%)',

  `share_capital` double default null comment '实收资本或股本',
  `share_capital_yoy` double default null comment '实收资本或股本(环比%)',
  `capital_reserve` double default null comment '资本公积',
  `capital_reserve_yoy` double default null comment '资本公积(环比%)',
  `other_compre_income` double default null comment '其他综合收益',
  `other_compre_income_yoy` double default null comment '其他综合收益(环比%)',
  `special_reserve` double default null comment '专项储备',
  `special_reserve_yoy` double default null comment '专项储备(环比%)',
  `surplus_reserve` double default null comment '盈余公积',
  `surplus_reserve_yoy` double default null comment '盈余公积(环比%)',
  `unassign_rpofit` double default null comment '未分配利润',
  `unassign_rpofit_yoy` double default null comment '未分配利润(环比%)',
  `total_parent_equity` double default null comment '归属于母公司股东权益总计',
  `total_parent_equity_yoy` double default null comment '归属于母公司股东权益总计(环比%)',
  `minority_equity` double default null comment '少数股东权益',
  `minority_equity_yoy` double default null comment '少数股东权益(环比%)',
  `total_equity` double default null comment '股东权益合计',
  `total_equity_yoy` double default null comment '股东权益合计(环比%)',
  `total_liab_equity` double default null comment '负债和股东权益总计',
  `total_liab_equity_yoy` double default null comment '负债和股东权益总计(环比%)',
  `opinion_type` varchar(20) character set utf8 collate utf8_bin comment '审计意见(境内)',

  primary key (`id`) using btree,
  unique key `employee_name` (`security_code`,`report_date`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-资产负债-普通类-报告期表';
