# 投顾管家相关配置
inv:
  #沪深A股基本信息
  stock-list: http://20.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=1000000&po=1&np=1&fltt=2&invt=2&fid=f3&fs=m:0+t:6,m:0+t:13,m:0+t:80,m:1+t:2,m:1+t:23&fields=f12,f14
  #沪深A股公司概况
  company-detail: http://f10.eastmoney.com/CompanySurvey/CompanySurveyAjax?code=

  #########################################################公司概况 开始##################################################
  company-web: https://emweb.eastmoney.com/PC_HSF10/CompanySurvey/Index?type=web&code=
  company-company-ajax: https://emweb.eastmoney.com/PC_HSF10/CompanySurvey/PageAjax?code=
  #########################################################公司概况 结束##################################################

  #########################################################财务分析 开始##################################################
  #财务分析所在页面
  finance-web: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/Index?type=web&code=
  #重要指标
  finance-zyzb-ajax-bgq: https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/ZYZBAjaxNew?type=0&code=
  finance-zyzb-ajax-nd: https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/ZYZBAjaxNew?type=1&code=
  finance-zyzb-ajax-jd: https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/ZYZBAjaxNew?type=2&code=
  #杜邦分析
  finance-dbfx-ajax: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/DBFXAjaxNew?code=
  #资产负债
  finance-zcfz-date-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/zcfzbDateAjaxNew?companyType=&reportDateType=0&code=
  finance-zcfz-date-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/zcfzbDateAjaxNew?companyType=&reportDateType=1&code=
  finance-zcfz-ajax-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/zcfzbAjaxNew?companyType=&reportDateType=0&reportType=1&dates=&code=
  finance-zcfz-ajax-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/zcfzbAjaxNew?companyType=&reportDateType=1&reportType=1&dates=&code=
  #利润
  finance-lr-date-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbDateAjaxNew?companyType=&reportDateType=0&code=
  finance-lr-date-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbDateAjaxNew?companyType=&reportDateType=1&code=
  finance-lr-date-jd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbDateAjaxNew?companyType=&reportDateType=2&code=
  finance-lr-ajax-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbAjaxNew?companyType=&reportDateType=0&reportType=1&dates=&code=
  finance-lr-ajax-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbAjaxNew?companyType=&reportDateType=1&reportType=1&dates=&code=
  finance-lr-ajax-jd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbAjaxNew?companyType=&reportDateType=0&reportType=2&dates=&code=
  #现金流量
  finance-xjll-date-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/xjllbDateAjaxNew?companyType=&reportDateType=0&code=
  finance-xjll-date-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/xjllbDateAjaxNew?companyType=&reportDateType=1&code=
  finance-xjll-date-jd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/xjllbDateAjaxNew?companyType=&reportDateType=2&code=
  finance-xjll-ajax-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/xjllbAjaxNew?companyType=&reportDateType=0&reportType=1&dates=&code=
  finance-xjll-ajax-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/xjllbAjaxNew?companyType=&reportDateType=1&reportType=1&dates=&code=
  finance-xjll-ajax-jd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/xjllbAjaxNew?companyType=&reportDateType=0&reportType=2&dates=&code=
  #百分比
  finance-bfb-ajax-bgq: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/bfbbbAjaxNew?ctype=&type=0&code=
  finance-bfb-ajax-nd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/bfbbbAjaxNew?ctype=&type=1&code=
  finance-bfb-ajax-jd: https://emweb.eastmoney.com/PC_HSF10/NewFinanceAnalysis/bfbbbAjaxNew?ctype=&type=2&code=
  #########################################################财务分析 结束##################################################

  #########################################################公司大事 开始##################################################
  #融资融券
  #大宗交易-每日明细
  dzjy-mrmx: https://datacenter-web.eastmoney.com/api/data/v1/get?sortColumns=TRADE_DATE%2CDEAL_AMT&sortTypes=1%2C-1&filter=(SECURITY_CODE%3D%22code=%22)&columns=ALL&source=WEB&client=WEB&reportName=RPT_DATA_BLOCKTRADE&pageSize=&pageNumber=
  #大宗交易-每日统计
  dzjy-mrtj: https://datacenter-web.eastmoney.com/api/data/v1/get?sortColumns=TRADE_DATE&sortTypes=-1&filter=(SECURITY_CODE%3D%22code=%22)&columns=ALL&source=WEB&client=WEB&reportName=RPT_BLOCKTRADE_STA&pageSize=-1&pageNumber=
  #融资融券
  rzrq: https://datapc.eastmoney.com/emdatacenter/rzrq/tradelist?p=&ps=-1&st=DATE&sr=-1&code=


  #########################################################公司大事 结束##################################################


