/*
 财务分析-重要指标-年度表
*/

DROP TABLE IF EXISTS `inv_finance_zyzb_year`;
CREATE TABLE `inv_finance_zyzb_year` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `security_code` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT '股票代码',
  `report_date` datetime DEFAULT NULL COMMENT '报告日期',
  `notice_date` datetime DEFAULT NULL COMMENT '发布日期',
  `update_date` datetime DEFAULT NULL COMMENT '修改日期',
  `mgwfplr` double DEFAULT NULL COMMENT '每股未分配利润(元)',
  `mgjyxjje` double DEFAULT NULL COMMENT '每股经营现金流(元)',
  `epsxs` double DEFAULT NULL COMMENT '稀释每股收益(元)',
  `epskcjb` double DEFAULT NULL COMMENT '扣非每股收益(元)',
  `mgzbgj` double DEFAULT NULL COMMENT '每股公积金(元)',
  `bps` double DEFAULT NULL COMMENT '每股净资产(元)',
  `epsjb` double DEFAULT NULL COMMENT '基本每股收益(元)',
  `yyzsrgdhbzc` double DEFAULT NULL COMMENT '营业总收入滚动环比增长(%)',
  `totaloperatereve` double DEFAULT NULL COMMENT '营业总收入(元)',
  `kfjlrgdhbzc` double DEFAULT NULL COMMENT '扣非净利润滚动环比增长(%)',
  `kcfjcxsyjlr` double DEFAULT NULL COMMENT '扣非净利润(元)',
  `epsjbtz` double DEFAULT NULL COMMENT '归属净利润同比增长(%)',
  `kcfjcxsyjlrtz` double DEFAULT NULL COMMENT '扣非净利润同比增长(%)',
  `parentnetprofit` double DEFAULT NULL COMMENT '归属净利润(元)',
  `netprofitrphbzc` double DEFAULT NULL COMMENT '归属净利润滚动环比增长(%)',
  `totaloperaterevetz` double DEFAULT NULL COMMENT '营业总收入同比增长(%)',
  `roekcjq` double DEFAULT NULL COMMENT '净资产收益率(扣非/加权)(%)',
  `zzcjll` double DEFAULT NULL COMMENT '总资产收益率(加权)(%)',
  `roejq` double DEFAULT NULL COMMENT '净资产收益率(加权)(%)',
  `xsmll` double DEFAULT NULL COMMENT '毛利率(%)',
  `xsjll` double DEFAULT NULL COMMENT '净利率(%)',
  `cqbl` double DEFAULT NULL COMMENT '产权比率',
  `zcfzl` double DEFAULT NULL COMMENT '资产负债率(%)',
  `qycs` double DEFAULT NULL COMMENT '权益乘数',
  `sd` double DEFAULT NULL COMMENT '速动比率',
  `xjllb` double DEFAULT NULL COMMENT '现金流量比率',
  `ld` double DEFAULT NULL COMMENT '流动比率',
  `zzczzts` double DEFAULT NULL COMMENT '总资产周转天数(天)',
  `yszkzzl` double DEFAULT NULL COMMENT '应收账款周转率(次)',
  `yszkzzts` double DEFAULT NULL COMMENT '应收账款周转天数(天)',
  `chzzts` double DEFAULT NULL COMMENT '存货周转天数(天)',
  `chzzl` double DEFAULT NULL COMMENT '存货周转率(次)',
  `toazzl` double DEFAULT NULL COMMENT '总资产周转率(次)',
  `yszkyysr` double DEFAULT NULL COMMENT '预收账款/营业总收入',
  `rzrqywfxzb` double DEFAULT NULL COMMENT '融资融券业务风险准备(元)',
  `zygdsylzqjzb` double DEFAULT NULL COMMENT '自营固定收益类证券规模/净资产',
  `totaldeposits` double DEFAULT NULL COMMENT '存款总额(元)',
  `mlr` double DEFAULT NULL COMMENT '毛利润(元)',
  `earned_premium` double DEFAULT NULL COMMENT '已赚保费(元)',
  `jzbjzc` double DEFAULT NULL COMMENT '净资本/净资产',
  `taxrate` double DEFAULT NULL COMMENT '实际税率(%)',
  `zygpgmjzc` double DEFAULT NULL COMMENT '自营股票规模/净资产',
  `ltdrr` double DEFAULT NULL COMMENT '存贷款比例',
  `solvency_ar` double DEFAULT NULL COMMENT '偿付能力充足率(%)',
  `jjywfxzb` double DEFAULT NULL COMMENT '经纪业务风险准备(元)',
  `zqzyywfxzb` double DEFAULT NULL COMMENT '证券自营业务风险准备(元)',
  `surrender_rate_life` double DEFAULT NULL COMMENT '退保率(%)',
  `jyxjlyysr` double DEFAULT NULL COMMENT '经营净现金流/营业总收入',
  `nzbje` double DEFAULT NULL COMMENT '资本净额(元)',
  `nonperloan` double DEFAULT NULL COMMENT '不良贷款率(%)',
  `total_roi` double DEFAULT NULL COMMENT '总投资收益率(%)',
  `zqcxywfxzb` double DEFAULT NULL COMMENT '证券承销业务风险准备(元)',
  `net_roi` double DEFAULT NULL COMMENT '净投资收益率(%)',
  `grossloans` double DEFAULT NULL COMMENT '贷款总额(元)',
  `hxyjbczl` double DEFAULT NULL COMMENT '核心资本充足率(%)',
  `parentnetprofittz` double DEFAULT NULL COMMENT '归属净利润同比增长(%)',
  `compensate_expense` double DEFAULT NULL COMMENT '赔付支出(元)',
  `jzc` double DEFAULT NULL COMMENT '净资产(元)',
  `jzb` double DEFAULT NULL COMMENT '净资本(元)',
  `bldkbbl` double DEFAULT NULL COMMENT '不良贷款拨备覆盖率(%)',
  `newcapitalader` double DEFAULT NULL COMMENT '资本充足率(%)',
  `xsjxlyysr` double DEFAULT NULL COMMENT '销售净现金流/营业总收入',
  `yyfxzb` double DEFAULT NULL COMMENT '营运风险准备(元)',
  `zcfzltz` double DEFAULT NULL COMMENT '-',
  `nbv_rate` double DEFAULT NULL COMMENT '-',
  `roejqtz` double DEFAULT NULL COMMENT '-',
  `djd_deductdpnp_yoy` double DEFAULT NULL COMMENT '-',
  `bpstz` double DEFAULT NULL COMMENT '-',
  `roic` double DEFAULT NULL COMMENT '-',
  `roictz` double DEFAULT NULL COMMENT '-',
  `report_year` double DEFAULT NULL COMMENT '-',
  `mgjyxjjetz` double DEFAULT NULL COMMENT '-',
  `djd_dpnp_yoy` double DEFAULT NULL COMMENT '-',
  `mgzbgjtz` double DEFAULT NULL COMMENT '-',
  `zzcjlltz` double DEFAULT NULL COMMENT '-',
  `djd_dpnp_qoq` double DEFAULT NULL COMMENT '-',
  `mgwfplrtz` double DEFAULT NULL COMMENT '-',
  `djd_deductdpnp_qoq` double DEFAULT NULL COMMENT '-',
  `nbv_life` double DEFAULT NULL COMMENT '-',
  `nhjz_current_amt` double DEFAULT NULL COMMENT '-',
  `djd_toi_qoq` double DEFAULT NULL COMMENT '-',
  `djd_toi_yoy` double DEFAULT NULL COMMENT '-',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务分析-重要指标-年度表';