/*
财务分析-重要指标-季度列表
*/

DROP TABLE IF EXISTS `inv_finance_zyzb_quarter`;
CREATE TABLE `inv_finance_zyzb_quarter` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `security_code` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '股票代码',
-- companyType=4

  `report_date` datetime DEFAULT NULL COMMENT '报告日期',
  `notice_date` datetime DEFAULT NULL COMMENT '发布日期',
  `update_date` datetime DEFAULT NULL COMMENT '修改日期',
-- 资产
  `MONETARYFUNDS` double DEFAULT NULL COMMENT '货币资金',
  `MONETARYFUNDS_YOY` double DEFAULT NULL COMMENT '货币资金',
  `DERIVE_FINASSET` double DEFAULT NULL COMMENT '衍生金融资产',
  `DERIVE_FINASSET_YOY` double DEFAULT NULL COMMENT '衍生金融资产',
  `NOTE_ACCOUNTS_RECE` double DEFAULT NULL COMMENT '应收票据及应收账款',
  `NOTE_ACCOUNTS_RECE_YOY` double DEFAULT NULL COMMENT '应收票据及应收账款',
  `NOTE_RECE` double DEFAULT NULL COMMENT '应收票据',
  `NOTE_RECE_YOY` double DEFAULT NULL COMMENT '应收票据',
  `ACCOUNTS_RECE` double DEFAULT NULL COMMENT '应收账款',
  `ACCOUNTS_RECE_YOY` double DEFAULT NULL COMMENT '应收账款',
  `FINANCE_RECE` double DEFAULT NULL COMMENT '应收款项融资',
  `FINANCE_RECE_YOY` double DEFAULT NULL COMMENT '应收款项融资',
  `PREPAYMENT` double DEFAULT NULL COMMENT '预付款项',
  `PREPAYMENT_YOY` double DEFAULT NULL COMMENT '预付款项',
  `TOTAL_OTHER_RECE` double DEFAULT NULL COMMENT '其他应收款合计',
  `TOTAL_OTHER_RECE_YOY` double DEFAULT NULL COMMENT '其他应收款合计',
  `DIVIDEND_RECE` double DEFAULT NULL COMMENT '应收股利',
  `DIVIDEND_RECE_YOY` double DEFAULT NULL COMMENT '应收股利',
  `INVENTORY` double DEFAULT NULL COMMENT '存货',
  `INVENTORY_YOY` double DEFAULT NULL COMMENT '存货',
  `CONTRACT_ASSET` double DEFAULT NULL COMMENT '合同资产',
  `CONTRACT_ASSET_YOY` double DEFAULT NULL COMMENT '合同资产',
  `NONCURRENT_ASSET_1YEAR` double DEFAULT NULL COMMENT '一年内到期的非流动资产',
  `NONCURRENT_ASSET_1YEAR_YOY` double DEFAULT NULL COMMENT '一年内到期的非流动资产',
  `OTHER_CURRENT_ASSET` double DEFAULT NULL COMMENT '其他流动资产',
  `OTHER_CURRENT_ASSET_YOY` double DEFAULT NULL COMMENT '其他流动资产',
  `TOTAL_CURRENT_ASSETS` double DEFAULT NULL COMMENT '流动资产合计',
  `TOTAL_CURRENT_ASSETS_YOY` double DEFAULT NULL COMMENT '流动资产合计',
  `LONG_RECE` double DEFAULT NULL COMMENT '长期应收款',
  `LONG_RECE_YOY` double DEFAULT NULL COMMENT '长期应收款',
  `LONG_EQUITY_INVEST` double DEFAULT NULL COMMENT '长期股权投资',
  `LONG_EQUITY_INVEST_YOY` double DEFAULT NULL COMMENT '长期股权投资',
  `OTHER_EQUITY_INVEST` double DEFAULT NULL COMMENT '其他权益工具投资',
  `OTHER_EQUITY_INVEST_YOY` double DEFAULT NULL COMMENT '其他权益工具投资',
  `INVEST_REALESTATE` double DEFAULT NULL COMMENT '投资性房地产',
  `INVEST_REALESTATE_YOY` double DEFAULT NULL COMMENT '投资性房地产',
  `FIXED_ASSET` double DEFAULT NULL COMMENT '固定资产',
  `FIXED_ASSET_YOY` double DEFAULT NULL COMMENT '固定资产',
  `CIP` double DEFAULT NULL COMMENT '在建工程',
  `CIP_YOY` double DEFAULT NULL COMMENT '在建工程',
  `USERIGHT_ASSET` double DEFAULT NULL COMMENT '使用权资产',
  `USERIGHT_ASSET_YOY` double DEFAULT NULL COMMENT '使用权资产',
  `INTANGIBLE_ASSET` double DEFAULT NULL COMMENT '无形资产',
  `INTANGIBLE_ASSET_YOY` double DEFAULT NULL COMMENT '无形资产',
  `DEVELOP_EXPENSE` double DEFAULT NULL COMMENT '开发支出',
  `DEVELOP_EXPENSE_YOY` double DEFAULT NULL COMMENT '开发支出',
  `LONG_PREPAID_EXPENSE` double DEFAULT NULL COMMENT '长期待摊费用',
  `LONG_PREPAID_EXPENSE_YOY` double DEFAULT NULL COMMENT '长期待摊费用',
  `DEFER_TAX_ASSET` double DEFAULT NULL COMMENT '递延所得税资产',
  `DEFER_TAX_ASSET_YOY` double DEFAULT NULL COMMENT '递延所得税资产',
  `OTHER_NONCURRENT_ASSET` double DEFAULT NULL COMMENT '其他非流动资产',
  `OTHER_NONCURRENT_ASSET_YOY` double DEFAULT NULL COMMENT '其他非流动资产',
  `TOTAL_NONCURRENT_ASSETS` double DEFAULT NULL COMMENT '非流动资产合计',
  `TOTAL_NONCURRENT_ASSETS_YOY` double DEFAULT NULL COMMENT '非流动资产合计',
  `TOTAL_ASSETS` double DEFAULT NULL COMMENT '资产总计',
  `TOTAL_ASSETS_YOY` double DEFAULT NULL COMMENT '资产总计',

  `SHORT_LOAN` double DEFAULT NULL COMMENT '短期借款',
  `SHORT_LOAN_YOY` double DEFAULT NULL COMMENT '短期借款',
  `NOTE_ACCOUNTS_PAYABLE` double DEFAULT NULL COMMENT '应付票据及应付账款',
  `NOTE_ACCOUNTS_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付票据及应付账款',
  `NOTE_PAYABLE` double DEFAULT NULL COMMENT '应付票据',
  `NOTE_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付票据',
  `ACCOUNTS_PAYABLE` double DEFAULT NULL COMMENT '应付账款',
  `ACCOUNTS_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付账款',
  `CONTRACT_LIAB` double DEFAULT NULL COMMENT '合同负债',
  `CONTRACT_LIAB_YOY` double DEFAULT NULL COMMENT '合同负债',
  `STAFF_SALARY_PAYABLE` double DEFAULT NULL COMMENT '应付职工薪酬',
  `STAFF_SALARY_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付职工薪酬',
  `TAX_PAYABLE` double DEFAULT NULL COMMENT '应交税费',
  `TAX_PAYABLE_YOY` double DEFAULT NULL COMMENT '应交税费',
  `TOTAL_OTHER_PAYABLE` double DEFAULT NULL COMMENT '其他应付款合计',
  `TOTAL_OTHER_PAYABLE_YOY` double DEFAULT NULL COMMENT '其他应付款合计',
  `DIVIDEND_PAYABLE` double DEFAULT NULL COMMENT '应付股利',
  `DIVIDEND_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付股利',
  `NONCURRENT_LIAB_1YEAR` double DEFAULT NULL COMMENT '一年内到期的非流动负债',
  `NONCURRENT_LIAB_1YEAR_YOY` double DEFAULT NULL COMMENT '一年内到期的非流动负债',
  `OTHER_CURRENT_LIAB_YOY` double DEFAULT NULL COMMENT '其他流动负债',
  `OTHER_CURRENT_LIAB` double DEFAULT NULL COMMENT '其他流动负债',
  `TOTAL_CURRENT_LIAB` double DEFAULT NULL COMMENT '流动负债合计',
  `TOTAL_CURRENT_LIAB_YOY` double DEFAULT NULL COMMENT '流动负债合计',
  `LONG_LOAN` double DEFAULT NULL COMMENT '长期借款',
  `LONG_LOAN_YOY` double DEFAULT NULL COMMENT '长期借款',
  `LEASE_LIAB` double DEFAULT NULL COMMENT '租赁负债',
  `LEASE_LIAB_YOY` double DEFAULT NULL COMMENT '租赁负债',
  `LONG_PAYABLE` double DEFAULT NULL COMMENT '长期应付款',
  `LONG_PAYABLE_YOY` double DEFAULT NULL COMMENT '长期应付款',
  `LONG_STAFFSALARY_PAYABLE` double DEFAULT NULL COMMENT '长期应付职工薪酬',
  `LONG_STAFFSALARY_PAYABLE_YOY` double DEFAULT NULL COMMENT '长期应付职工薪酬',
  `PREDICT_LIAB` double DEFAULT NULL COMMENT '预计负债',
  `PREDICT_LIAB_YOY` double DEFAULT NULL COMMENT '预计负债',
  `DEFER_INCOME` double DEFAULT NULL COMMENT '递延收益',
  `DEFER_INCOME_YOY` double DEFAULT NULL COMMENT '递延收益',
  `DEFER_TAX_LIAB` double DEFAULT NULL COMMENT '递延所得税负债',
  `DEFER_TAX_LIAB_YOY` double DEFAULT NULL COMMENT '递延所得税负债',
  `TOTAL_NONCURRENT_LIAB` double DEFAULT NULL COMMENT '非流动负债合计',
  `TOTAL_NONCURRENT_LIAB_YOY` double DEFAULT NULL COMMENT '非流动负债合计',
  `TOTAL_LIABILITIES` double DEFAULT NULL COMMENT '负债合计',
  `TOTAL_LIABILITIES_YOY` double DEFAULT NULL COMMENT '负债合计',

  `SHARE_CAPITAL` double DEFAULT NULL COMMENT '实收资本（或股本）',
  `SHARE_CAPITAL_YOY` double DEFAULT NULL COMMENT '实收资本（或股本）',
  `CAPITAL_RESERVE` double DEFAULT NULL COMMENT '资本公积',
  `CAPITAL_RESERVE_YOY` double DEFAULT NULL COMMENT '资本公积',
  `OTHER_COMPRE_INCOME` double DEFAULT NULL COMMENT '其他综合收益',
  `OTHER_COMPRE_INCOME_YOY` double DEFAULT NULL COMMENT '其他综合收益',
  `SPECIAL_RESERVE` double DEFAULT NULL COMMENT '专项储备',
  `SPECIAL_RESERVE_YOY` double DEFAULT NULL COMMENT '专项储备',
  `SURPLUS_RESERVE` double DEFAULT NULL COMMENT '盈余公积',
  `SURPLUS_RESERVE_YOY` double DEFAULT NULL COMMENT '盈余公积',
  `UNASSIGN_RPOFIT` double DEFAULT NULL COMMENT '未分配利润',
  `UNASSIGN_RPOFIT_YOY` double DEFAULT NULL COMMENT '未分配利润',
  `TOTAL_PARENT_EQUITY` double DEFAULT NULL COMMENT '归属于母公司股东权益总计',
  `TOTAL_PARENT_EQUITY_YOY` double DEFAULT NULL COMMENT '归属于母公司股东权益总计',
  `MINORITY_EQUITY` double DEFAULT NULL COMMENT '少数股东权益',
  `MINORITY_EQUITY_YOY` double DEFAULT NULL COMMENT '少数股东权益',
  `TOTAL_EQUITY` double DEFAULT NULL COMMENT '股东权益合计',
  `TOTAL_EQUITY_YOY` double DEFAULT NULL COMMENT '股东权益合计',
  `TOTAL_LIAB_EQUITY` double DEFAULT NULL COMMENT '负债和股东权益总计',
  `TOTAL_LIAB_EQUITY_YOY` double DEFAULT NULL COMMENT '负债和股东权益总计',
  `OPINION_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin COMMENT '审计意见(境内)',
-- ---------------------------------------------------------------------------------

  `CASH_DEPOSIT_PBC` double DEFAULT NULL COMMENT '现金及存放中央银行款项',
  `CASH_DEPOSIT_PBC_YOY` double DEFAULT NULL COMMENT '现金及存放中央银行款项',
  `DEPOSIT_INTERBANK` double DEFAULT NULL COMMENT '存放同业款项',
  `DEPOSIT_INTERBANK_YOY` double DEFAULT NULL COMMENT '存放同业款项',
  `PRECIOUS_METAL` double DEFAULT NULL COMMENT '贵金属',
  `PRECIOUS_METAL_YOY` double DEFAULT NULL COMMENT '贵金属',
  `LEND_FUND` double DEFAULT NULL COMMENT '拆出资金',
  `LEND_FUND_YOY` double DEFAULT NULL COMMENT '拆出资金',
  `FVTPL_FINASSET` double DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融资产',
  `FVTPL_FINASSET_YOY` double DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融资产',

  `BUY_RESALE_FINASSET` double DEFAULT NULL COMMENT '买入返售金融资产',
  `BUY_RESALE_FINASSET_YOY` double DEFAULT NULL COMMENT '买入返售金融资产',
  `LOAN_ADVANCE` double DEFAULT NULL COMMENT '发放贷款及垫款',
  `LOAN_ADVANCE_YOY` double DEFAULT NULL COMMENT '发放贷款及垫款',
  `AMORTIZE_COST_FINASSET` double DEFAULT NULL COMMENT '以摊余成本计量的金融资产',
  `AMORTIZE_COST_FINASSETYOY` double DEFAULT NULL COMMENT '以摊余成本计量的金融资产',
  `FVTOCI_FINASSET` double DEFAULT NULL COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产',
  `FVTOCI_FINASSET_YOY` double DEFAULT NULL COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产',



  `GOODWILL` double DEFAULT NULL COMMENT '商誉',
  `GOODWILL_YOY` double DEFAULT NULL COMMENT '商誉',
  `OTHER_ASSET` double DEFAULT NULL COMMENT '其他资产',
  `OTHER_ASSET_YOY` double DEFAULT NULL COMMENT '其他资产',
  `ASSET_OTHER` double DEFAULT NULL COMMENT '资产其他项目',
  `ASSET_OTHER_YOY` double DEFAULT NULL COMMENT '资产其他项目',


  `LOAN_PBC` double DEFAULT NULL COMMENT '向中央银行借款',
  `LOAN_PBC_YOY` double DEFAULT NULL COMMENT '向中央银行借款',
  `IOFI_DEPOSIT` double DEFAULT NULL COMMENT '同业及其他金融机构存放款项',
  `IOFI_DEPOSIT_YOY` double DEFAULT NULL COMMENT '同业及其他金融机构存放款项',
  `BORROW_FUND` double DEFAULT NULL COMMENT '拆入资金',
  `BORROW_FUND_YOY` double DEFAULT NULL COMMENT '拆入资金',
  `FVTPL_FINLIAB` double DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融负债',
  `FVTPL_FINLIAB_YOY` double DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融负债',
  `DERIVE_FINLIAB` double DEFAULT NULL COMMENT '衍生金融负债',
  `DERIVE_FINLIAB_YOY` double DEFAULT NULL COMMENT '衍生金融负债',
  `SELL_REPO_FINASSET` double DEFAULT NULL COMMENT '卖出回购金融资产款',
  `SELL_REPO_FINASSET_YOY` double DEFAULT NULL COMMENT '卖出回购金融资产款',
  `ACCEPT_DEPOSIT` double DEFAULT NULL COMMENT '吸收存款',
  `ACCEPT_DEPOSIT_YOY` double DEFAULT NULL COMMENT '吸收存款',



  `BOND_PAYABLE` double DEFAULT NULL COMMENT '应付债券',
  `BOND_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付债券',
  `OTHER_LIAB` double DEFAULT NULL COMMENT '其他负债',
  `OTHER_LIAB_YOY` double DEFAULT NULL COMMENT '其他负债',



  `OTHER_EQUITY_OTHER` double DEFAULT NULL COMMENT '其他权益工具',
  `OTHER_EQUITY_OTHER_YOY` double DEFAULT NULL COMMENT '其他权益工具',
  `PREFERRED_SHARES` double DEFAULT NULL COMMENT '优先股',
  `PREFERRED_SHARES_YOY` double DEFAULT NULL COMMENT '优先股',
  `PERPETUAL_BOND` double DEFAULT NULL COMMENT '永续债',
  `PERPETUAL_BOND_YOY` double DEFAULT NULL COMMENT '永续债',



  `GENERAL_RISK_RESERVE` double DEFAULT NULL COMMENT '一般风险准备',
  `GENERAL_RISK_RESERVE_YOY` double DEFAULT NULL COMMENT '一般风险准备',






  `INTEREST_RECE` double DEFAULT NULL COMMENT '应收利息',
  `INTEREST_RECE_YOY` double DEFAULT NULL COMMENT '应收利息',
  `PREMIUM_RECE` double DEFAULT NULL COMMENT '应收保费',
  `PREMIUM_RECE_YOY` double DEFAULT NULL COMMENT '应收保费',
  `REINSURE_RECE` double DEFAULT NULL COMMENT '应收分保账款',
  `REINSURE_RECE_YOY` double DEFAULT NULL COMMENT '应收分保账款',
  `RUD_RESERVE_RECE` double DEFAULT NULL COMMENT '应收分保未到期责任准备金',
  `RUD_RESERVE_RECE_YOY` double DEFAULT NULL COMMENT '应收分保未到期责任准备金',
  `RUC_RESERVE_RECE` double DEFAULT NULL COMMENT '应收分保未决赔偿准备金',
  `RUC_RESERVE_RECE_YOY` double DEFAULT NULL COMMENT '应收分保未决赔偿准备金',

  `TRADE_FINASSET_NOTFVTPL` double DEFAULT NULL COMMENT '交易性金融资产',
  `TRADE_FINASSET_NOTFVTPL_YOY` double DEFAULT NULL COMMENT '交易性金融资产',
  `OTHER_RECE` double DEFAULT NULL COMMENT '其他应收款',
  `OTHER_RECE_YOY` double DEFAULT NULL COMMENT '其他应收款',
  `TIME_DEPOSIT` double DEFAULT NULL COMMENT '定期存款',
  `TIME_DEPOSIT_YOY` double DEFAULT NULL COMMENT '定期存款',
  `AVAILABLE_SALE_FINASSET` double DEFAULT NULL COMMENT '可供出售金融资产',
  `AVAILABLE_SALE_FINASSET_YOY` double DEFAULT NULL COMMENT '可供出售金融资产',
  `HOLD_MATURITY_INVEST` double DEFAULT NULL COMMENT '持有至到期投资',
  `HOLD_MATURITY_INVEST_YOY` double DEFAULT NULL COMMENT '持有至到期投资',


  `REFUND_CAPITAL_DEPOSIT` double DEFAULT NULL COMMENT '存出资本保证金',
  `REFUND_CAPITAL_DEPOSIT_YOY` double DEFAULT NULL COMMENT '存出资本保证金',








  `ADVANCE_RECE` double DEFAULT NULL COMMENT '预收账款',
  `ADVANCE_RECE_YOY` double DEFAULT NULL COMMENT '预收账款',
  `ADVANCE_PREMIUM` double DEFAULT NULL COMMENT '预收保费',
  `ADVANCE_PREMIUM_YOY` double DEFAULT NULL COMMENT '预收保费',
  `FEE_COMMISSION_PAYABLE` double DEFAULT NULL COMMENT '应付手续费及佣金',
  `FEE_COMMISSION_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付手续费及佣金',
  `REINSURE_PAYABLE` double DEFAULT NULL COMMENT '应付分保账款',
  `REINSURE_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付分保账款',

  `INTEREST_PAYABLE` double DEFAULT NULL COMMENT '应付利息',
  `INTEREST_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付利息',
  `COMPENSATE_PAYABLE` double DEFAULT NULL COMMENT '应付赔付款',
  `COMPENSATE_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付赔付款',




  `LIAB_OTHER` double DEFAULT NULL COMMENT '负债其他项目',
  `LIAB_OTHER_YOY` double DEFAULT NULL COMMENT '负债其他项目',











  `CUSTOMER_DEPOSIT` double DEFAULT NULL COMMENT '客户资金存款',
  `CUSTOMER_DEPOSIT_YOY` double DEFAULT NULL COMMENT '',
  `SETTLE_EXCESS_RESERVE` double DEFAULT NULL COMMENT '结算备付金',
  `SETTLE_EXCESS_RESERVE_YOY` double DEFAULT NULL COMMENT '',
  `CUSTOMER_EXCESS_RESERVE` double DEFAULT NULL COMMENT '客户备付金',
  `CUSTOMER_EXCESS_RESERVE_YOY` double DEFAULT NULL COMMENT '',
  `FIN_FUND` double DEFAULT NULL COMMENT '融出资金',
  `FIN_FUND_YOY` double DEFAULT NULL COMMENT '',


  `RECEIVABLES` double DEFAULT NULL COMMENT '应收款项',
  `RECEIVABLES_YOY` double DEFAULT NULL COMMENT '',
  `REFUND_DEPOSIT_PAY` double DEFAULT NULL COMMENT '存出保证金',
  `REFUND_DEPOSIT_PAY_YOY` double DEFAULT NULL COMMENT '',

  `CREDITOR_INVEST` double DEFAULT NULL COMMENT '债权投资',
  `CREDITOR_INVEST_YOY` double DEFAULT NULL COMMENT '债权投资',









-- 负债
  `SHORT_FIN_PAYABLE` double DEFAULT NULL COMMENT '应付短期融资款',
  `SHORT_FIN_PAYABLE_YOY` double DEFAULT NULL COMMENT '',

  `TRADE_FINLIAB_NOTFVTPL` double DEFAULT NULL COMMENT '交易性金融负债',
  `TRADE_FINLIAB_NOTFVTPL_YOY` double DEFAULT NULL COMMENT '交易性金融负债',


  `AGENT_TRADE_SECURITY` double DEFAULT NULL COMMENT '代理买卖证券款',
  `AGENT_TRADE_SECURITY_YOY` double DEFAULT NULL COMMENT '',
  `AGENT_UNDERWRITE_SECURITY` double DEFAULT NULL COMMENT '代理承销证券款',
  `AGENT_UNDERWRITE_SECURITY_YOY` double DEFAULT NULL COMMENT '代理承销证券款',







-- 所有者权益(或股东权益)









  `epsjb` double DEFAULT NULL COMMENT '摊薄每股收益(元)',
  `UPDATE_DATE` double DEFAULT NULL COMMENT '',
  `PARENT_EQUITY_BALANCE_YOY` double DEFAULT NULL COMMENT '归属于母公司股东权益平衡项目',

  `NET_PENDMORTGAGE_ASSET` double DEFAULT NULL COMMENT '待处理抵债资产净额',
  `HEDGE_RESERVE_YOY` double DEFAULT NULL COMMENT '套期储备',

  `PREFERRED_SHARES_PAYBALE_YOY` double DEFAULT NULL COMMENT '优先股(应付债券)-其中:优先股(应付债券)',
  `OSOPINION_TYPE` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin COMMENT '审计意见(境外)',
  `HEDGE_RESERVE` double DEFAULT NULL COMMENT '套期储备',


  `HOLDSALE_LIAB` double DEFAULT NULL COMMENT '持有待售负债',




  `OTHER_CREDITOR_INVEST_YOY` double DEFAULT NULL COMMENT '其他债权投资',


  `TRADE_FINASSET` double DEFAULT NULL COMMENT '交易性金融资产',
  `LIAB_BALANCE` double DEFAULT NULL COMMENT '负债平衡项目',


  `APPOINT_FVTPL_FINLIAB` double DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融负债',


  `AMORTIZE_COST_FINLIAB_YOY` double DEFAULT NULL COMMENT '以摊余成本计量的金融负债',

  `HOLDSALE_ASSET` double DEFAULT NULL COMMENT '持有待售资产',
  `LIAB_BALANCE_YOY` double DEFAULT NULL COMMENT '负债平衡项目',




  `TRADE_FINASSET_YOY` double DEFAULT NULL COMMENT '交易性金融资产',
  `INVEST_JOINT_YOY` double DEFAULT NULL COMMENT '对联营和合营企业的投资',
  `ASSET_BALANCE` double DEFAULT NULL COMMENT '资产平衡项目',

  `EQUITY_BALANCE` double DEFAULT NULL COMMENT '归属于母公司股东权益平衡项目',
  `PARENT_EQUITY_BALANCE` double DEFAULT NULL COMMENT '归属于母公司股东权益平衡项目',



  `PEND_MORTGAGE_ASSET_YOY` double DEFAULT NULL COMMENT '待处理抵债资产',
  `PEND_MORTGAGE_ASSET` double DEFAULT NULL COMMENT '待处理抵债资产',


  `HOLDSALE_LIAB_YOY` double DEFAULT NULL COMMENT '持有待售负债',
  `INVEST_RECE_YOY` double DEFAULT NULL COMMENT '应收款项类投资',



  `PERPETUAL_BOND_PAYBALE` double DEFAULT NULL COMMENT '永续债(应付债券)',


  `CD_NOTE_PAYABLE_YOY` double DEFAULT NULL COMMENT '存款证及应付票据',
  `ASSET_BALANCE_YOY` double DEFAULT NULL COMMENT '资产平衡项目',
  `HOLDSALE_ASSET_YOY` double DEFAULT NULL COMMENT '持有待售资产',
  `INVEST_JOINT` double DEFAULT NULL COMMENT '对联营和合营企业的投资',
  `CONVERT_DIFF_YOY` double DEFAULT NULL COMMENT '外币报表折算差额',
  `SUBBOND_PAYABLE_YOY` double DEFAULT NULL COMMENT '应付次级债券',

  `OUTWARD_REMIT_YOY` double DEFAULT NULL COMMENT '汇出汇款',
  `LIAB_EQUITY_OTHER` double DEFAULT NULL COMMENT '负债和股东权益其他项目',
  `CD_NOTE_PAYABLE` double DEFAULT NULL COMMENT '存款证及应付票据',

  `TREASURY_SHARES` double DEFAULT NULL COMMENT '减:库存股',
  `AMORTIZE_COST_FINLIAB` double DEFAULT NULL COMMENT '以摊余成本计量的金融负债',

  `INVEST_REVALUE_RESERVE_YOY` double DEFAULT NULL COMMENT '投资重估储备',

  `EQUITY_BALANCE_YOY` double DEFAULT NULL COMMENT '归属于母公司股东权益平衡项目',


  `OTHER_EQUITY_TOOL_YOY` double DEFAULT NULL COMMENT '其他权益工具',

  `INVEST_RECE` double DEFAULT NULL COMMENT '应收款项类投资',
  `OUTWARD_REMIT` double DEFAULT NULL COMMENT '汇出汇款',
  `LIAB_EQUITY_BALANCE_YOY` double DEFAULT NULL COMMENT '负债及股东权益平衡项目',

  `ADVICE_ASSIGN_DIVIDEND_YOY` double DEFAULT NULL COMMENT '未分配利润-建议分派股利',

  `LIAB_EQUITY_BALANCE` double DEFAULT NULL COMMENT '负债及股东权益平衡项目',
  `PARENT_EQUITY_OTHER` double DEFAULT NULL COMMENT '归属于母公司股东权益其他项目',
  `NET_PENDMORTGAGE_ASSET_YOY` double DEFAULT NULL COMMENT '待处理抵债资产净额',
  `CONVERT_DIFF` double DEFAULT NULL COMMENT '外币报表折算差额',
  `TRADE_FINLIAB` double DEFAULT NULL COMMENT '交易性金融负债',


  `APPOINT_FVTPL_FINLIAB_YOY` double DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融负债',
  `EQUITY_OTHER_YOY` double DEFAULT NULL COMMENT '股东权益其他项目',
  `INVEST_REVALUE_RESERVE` double DEFAULT NULL COMMENT '投资重估储备',
  `TRADE_FINLIAB_YOY` double DEFAULT NULL COMMENT '交易性金融负债',
  `TREASURY_SHARES_YOY` double DEFAULT NULL COMMENT '减:库存股',
  `ADVICE_ASSIGN_DIVIDEND` double DEFAULT NULL COMMENT '建议分派股利',
  `MORTGAGE_ASSET_IMPAIRMENT_YOY` double DEFAULT NULL COMMENT '抵债资产减值准备',

  `APPOINT_FVTPL_FINASSET` double DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融资产',
  `OTHER_EQUITY_TOOL` double DEFAULT NULL COMMENT '其他权益工具',
  `EQUITY_OTHER` double DEFAULT NULL COMMENT '股东权益其他项目',
  `MORTGAGE_ASSET_IMPAIRMENT` double DEFAULT NULL COMMENT '抵债资产减值准备',
  `SUBBOND_PAYABLE` double DEFAULT NULL COMMENT '应付次级债券',

  `PERPETUAL_BOND_PAYBALE_YOY` double DEFAULT NULL COMMENT '永续债(应付债券)',

  `LIAB_EQUITY_OTHER_YOY` double DEFAULT NULL COMMENT '负债和股东权益其他项目',



  `DEPOSIT_CERTIFICATE` double DEFAULT NULL COMMENT '存款证及应付票据',

  `OTHER_CREDITOR_INVEST` double DEFAULT NULL COMMENT '其他债权投资',

  `INVEST_SUBSIDIARY_YOY` double DEFAULT NULL COMMENT '对子公司的投资',
  `INVEST_SUBSIDIARY` double DEFAULT NULL COMMENT '对子公司的投资',
  `DEPOSIT_CERTIFICATE_YOY` double DEFAULT NULL COMMENT '存款证及应付票据',

  `PARENT_EQUITY_OTHER_YOY` double DEFAULT NULL COMMENT '归属于母公司股东权益其他项目',

  `PREFERRED_SHARES_PAYBALE` double DEFAULT NULL COMMENT '优先股(应付债券)',
  `APPOINT_FVTPL_FINASSET_YOY` double DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融资产',
  `INSURED_DEPOSIT_INVEST` double DEFAULT NULL COMMENT '',
  `AMORTIZE_COST_NCFINLIAB_YOY` double DEFAULT NULL COMMENT '',

  `IND_ACC_LIAB` double DEFAULT NULL COMMENT '',


  `CREDITOR_PLAN_INVEST` double DEFAULT NULL COMMENT '',

  `AGENT_BUSINESS_ASSET` double DEFAULT NULL COMMENT '',
  `RC_RESERVE_RECE` double DEFAULT NULL COMMENT '',
  `REFUND_DEPOSIT_RECE_YOY` double DEFAULT NULL COMMENT '',
  `NONCURRENT_LIAB_OTHER` double DEFAULT NULL COMMENT '',


  `HD_RESERVE` double DEFAULT NULL COMMENT '',


  `OTHER_NONCURRENT_LIAB` double DEFAULT NULL COMMENT '',

  `FIN_SECURITY` double DEFAULT NULL COMMENT '',

  `IND_ACC_ASSET_YOY` double DEFAULT NULL COMMENT '',
  `INTERNAL_PAYABLE` double DEFAULT NULL COMMENT '',
  `UD_RESERVE_YOY` double DEFAULT NULL COMMENT '',
  `SUBSIDY_RECE` double DEFAULT NULL COMMENT '',

  `SUBSIDY_RECE_YOY` double DEFAULT NULL COMMENT '',
  `PLEDGE_LOAN_YOY` double DEFAULT NULL COMMENT '',

  `REFUND_DEPOSIT_RECE` double DEFAULT NULL COMMENT '',




  `DIV_HOLDSALE_LIAB_YOY` double DEFAULT NULL COMMENT '',


  `CURRENT_LIAB_BALANCE` double DEFAULT NULL COMMENT '',
  `FVTOCI_NCFINASSET_YOY` double DEFAULT NULL COMMENT '',




  `ADVANCE_RECEIVABLES` double DEFAULT NULL COMMENT '',
  `TRADE_SEAT_FEE` double DEFAULT NULL COMMENT '',

  `RHD_RESERVE_RECE` double DEFAULT NULL COMMENT '',
  `PRODUCTIVE_BIOLOGY_ASSET_YOY` double DEFAULT NULL COMMENT '',
  `TRADE_SEAT_FEE_YOY` double DEFAULT NULL COMMENT '',

  `INSURANCE_CONTRACT_RESERVE` double DEFAULT NULL COMMENT '',
  `RHD_RESERVE_RECE_YOY` double DEFAULT NULL COMMENT '',
  `PREDICT_CURRENT_LIAB` double DEFAULT NULL COMMENT '',
  `IND_ACC_ASSET` double DEFAULT NULL COMMENT '',

  `PREDICT_CURRENT_LIAB_YOY` double DEFAULT NULL COMMENT '',


  `ASSIGN_CASH_DIVIDEND_YOY` double DEFAULT NULL COMMENT '',
  `OTHER_PAYABLE_YOY` double DEFAULT NULL COMMENT '',
  `RLD_RESERVE_RECE_YOY` double DEFAULT NULL COMMENT '',
  `UNCONFIRM_INVEST_LOSS_YOY` double DEFAULT NULL COMMENT '',
  `ACCEPT_DEPOSIT_INTERBANK_YOY` double DEFAULT NULL COMMENT '',
  `CURRENT_ASSET_OTHER_YOY` double DEFAULT NULL COMMENT '',
  `SUBROGATION_RECE_YOY` double DEFAULT NULL COMMENT '',


  `LD_RESERVE_YOY` double DEFAULT NULL COMMENT '',
  `SECURITY_CODE` double DEFAULT NULL COMMENT '',

  `INTERNAL_RECE` double DEFAULT NULL COMMENT '',

  `CURRENT_LIAB_OTHER_YOY` double DEFAULT NULL COMMENT '',
  `CURRENT_ASSET_OTHER` double DEFAULT NULL COMMENT '',

  `SUBROGATION_RECE` double DEFAULT NULL COMMENT '',
  `FIN_SECURITY_YOY` double DEFAULT NULL COMMENT '',


  `DEFER_INCOME_1YEAR` double DEFAULT NULL COMMENT '',

  `ACCRUED_EXPENSE` double DEFAULT NULL COMMENT '',

  `REPORT_DATE_NAME` double DEFAULT NULL COMMENT '',

  `PRODUCTIVE_BIOLOGY_ASSET` double DEFAULT NULL COMMENT '',
  `NOTICE_DATE` double DEFAULT NULL COMMENT '',
  `PROJECT_MATERIAL_YOY` double DEFAULT NULL COMMENT '',

  `FIXED_ASSET_DISPOSAL` double DEFAULT NULL COMMENT '',
  `AGENT_BUSINESS_ASSET_YOY` double DEFAULT NULL COMMENT '',

  `HD_RESERVE_YOY` double DEFAULT NULL COMMENT '',

  `PROJECT_MATERIAL` double DEFAULT NULL COMMENT '',
  `CURRENT_LIAB_BALANCE_YOY` double DEFAULT NULL COMMENT '',
  `NONCURRENT_LIAB_BALANCE_YOY` double DEFAULT NULL COMMENT '',
  `CREDIT_AGENT_SECURITY` double DEFAULT NULL COMMENT '',
  `CUSTOMER_CREDIT_DEPOSIT_YOY` double DEFAULT NULL COMMENT '',

  `INTERNAL_RECE_YOY` double DEFAULT NULL COMMENT '',

  `LD_RESERVE` double DEFAULT NULL COMMENT '',

  `CREDIT_EXCESS_RESERVE` double DEFAULT NULL COMMENT '',
  `AGENT_BUSINESS_LIAB_YOY` double DEFAULT NULL COMMENT '',
  `CONSUMPTIVE_BIOLOGICAL_ASSET` double DEFAULT NULL COMMENT '',

  `UNCONFIRM_INVEST_LOSS` double DEFAULT NULL COMMENT '',
  `EXPORT_REFUND_RECE` double DEFAULT NULL COMMENT '',
  `INSURED_PLEDGE_LOAN` double DEFAULT NULL COMMENT '',
  `DIV_HOLDSALE_ASSET_YOY` double DEFAULT NULL COMMENT '',

  `TRADE_RISK_RESERVE_YOY` double DEFAULT NULL COMMENT '',
  `FVTOCI_NCFINASSET` double DEFAULT NULL COMMENT '',
  `OTHER_NONCURRENT_FINASSET` double DEFAULT NULL COMMENT '',
  `ASSIGN_CASH_DIVIDEND` double DEFAULT NULL COMMENT '',
  `DIV_HOLDSALE_LIAB` double DEFAULT NULL COMMENT '',
  `OTHER_NONCURRENT_FINASSET_YOY` double DEFAULT NULL COMMENT '',

  `FIXED_ASSET_DISPOSAL_YOY` double DEFAULT NULL COMMENT '',
  `EXPORT_REFUND_RECE_YOY` double DEFAULT NULL COMMENT '',
  `OTHER_PAYABLE` double DEFAULT NULL COMMENT '',
  `RLD_RESERVE_RECE` double DEFAULT NULL COMMENT '',

  `INSURED_PLEDGE_LOAN_YOY` double DEFAULT NULL COMMENT '',


  `ADVANCE_RECEIVABLES_YOY` double DEFAULT NULL COMMENT '',
  `RC_RESERVE_RECE_YOY` double DEFAULT NULL COMMENT '',

  `SHORT_BOND_PAYABLE` double DEFAULT NULL COMMENT '',
  `CUSTOMER_CREDIT_DEPOSIT` double DEFAULT NULL COMMENT '',
  `LISTING_STATE` double DEFAULT NULL COMMENT '',




  `CREDITOR_PLAN_INVEST_YOY` double DEFAULT NULL COMMENT '',
  `DIV_HOLDSALE_ASSET` double DEFAULT NULL COMMENT '',
  `NONCURRENT_ASSET_OTHER_YOY` double DEFAULT NULL COMMENT '',
  `SPECIAL_PAYABLE` double DEFAULT NULL COMMENT '',
  `OTHER_NONCURRENT_LIAB_YOY` double DEFAULT NULL COMMENT '',
  `CURRENCY` double DEFAULT NULL COMMENT '',
  `UC_RESERVE` double DEFAULT NULL COMMENT '',
  `CURRENT_ASSET_BALANCE` double DEFAULT NULL COMMENT '',
  `AGENT_BUSINESS_LIAB` double DEFAULT NULL COMMENT '',
  `UC_RESERVE_YOY` double DEFAULT NULL COMMENT '',

  `AMORTIZE_COST_NCFINLIAB` double DEFAULT NULL COMMENT '',
  `ACCEPT_DEPOSIT_INTERBANK` double DEFAULT NULL COMMENT '',
  `INTERNAL_PAYABLE_YOY` double DEFAULT NULL COMMENT '',

  `SPECIAL_PAYABLE_YOY` double DEFAULT NULL COMMENT '',
  `NONCURRENT_ASSET_OTHER` double DEFAULT NULL COMMENT '',
  `TRADE_RISK_RESERVE` double DEFAULT NULL COMMENT '',
  `ACCRUED_EXPENSE_YOY` double DEFAULT NULL COMMENT '',
  `CURRENT_ASSET_BALANCE_YOY` double DEFAULT NULL COMMENT '',

  `OIL_GAS_ASSET` double DEFAULT NULL COMMENT '',
  `OIL_GAS_ASSET_YOY` double DEFAULT NULL COMMENT '',
  `DEFER_INCOME_1YEAR_YOY` double DEFAULT NULL COMMENT '',

  `AMORTIZE_COST_NCFINASSET` double DEFAULT NULL COMMENT '',
  `IND_ACC_LIAB_YOY` double DEFAULT NULL COMMENT '',
  `OSOOPINION_TYPE` double DEFAULT NULL COMMENT '',




  `PLEDGE_LOAN` double DEFAULT NULL COMMENT '',
  `NONCURRENT_LIAB_OTHER_YOY` double DEFAULT NULL COMMENT '',


  `CONSUMPTIVE_BIOLOGICAL_ASSET_YOY` double DEFAULT NULL COMMENT '',
  `UD_RESERVE` double DEFAULT NULL COMMENT '',
  `AMORTIZE_COST_NCFINASSET_YOY` double DEFAULT NULL COMMENT '',
  `SHORT_BOND_PAYABLE_YOY` double DEFAULT NULL COMMENT '',
  `SECURITY_NAME_ABBR` double DEFAULT NULL COMMENT '',
  `SECURITY_TYPE_CODE` double DEFAULT NULL COMMENT '',
  `NONCURRENT_LIAB_BALANCE` double DEFAULT NULL COMMENT '',
  `NONCURRENT_ASSET_BALANCE_YOY` double DEFAULT NULL COMMENT '',
  `INSURED_DEPOSIT_INVEST_YOY` double DEFAULT NULL COMMENT '',
  `CREDIT_AGENT_SECURITY_YOY` double DEFAULT NULL COMMENT '',
  `CREDIT_EXCESS_RESERVE_YOY` double DEFAULT NULL COMMENT '',
  `POLICY_BONUS_PAYABLE` double DEFAULT NULL COMMENT '',
  `CURRENT_LIAB_OTHER` double DEFAULT NULL COMMENT '',
  `POLICY_BONUS_PAYABLE_YOY` double DEFAULT NULL COMMENT '',


  `NONCURRENT_ASSET_BALANCE` double DEFAULT NULL COMMENT '',
  `INSURANCE_CONTRACT_RESERVE_YOY` double DEFAULT NULL COMMENT '',



  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='财务分析-重要指标-季度列表';
