/*
 公司概况
*/
drop table if exists inv_company;
create table inv_company (
  code varchar(10) not null comment '股票代码',
  org_name varchar(500) default null comment '公司名称',
  org_name_en varchar(500) default null comment '英文名称',
  str_codea varchar(10) default null comment 'A股代码',
  str_namea varchar(10) default null comment 'A股简称',
  expand_name_abbr varchar(10) default null comment 'A股扩位简称',
  formername varchar(1000) default null comment '曾用名',
  str_codeb varchar(10) default null comment 'B股代码',
  str_nameb varchar(10) default null comment 'B股简称',
  str_codeh varchar(10) default null comment 'H股代码',
  str_nameh varchar(10) default null comment 'H股简称',
  security_type varchar(200) default null comment '证券类别',
  em2016 varchar(500) default null comment '所属东财行业',
  trade_market varchar(100) default null comment '上市交易所',
  industrycsrc1 varchar(500) default null comment '所属证监会行业',
  president varchar(100) default null comment '总经理',
  legal_person varchar(100) default null comment '法人代表',
  secretary varchar(100) default null comment '董秘',
  chairman varchar(100) default null comment '董事长',
  secpresent varchar(100) default null comment '证券事务代表',
  indedirectors varchar(1000) default null comment '独立董事',
  org_tel varchar(500) default null comment '联系电话',
  org_email varchar(500) default null comment '电子信箱',
  org_fax varchar(500) default null comment '传真',
  org_web varchar(500) default null comment '公司网址',
  address varchar(500) default null comment '办公地址',
  reg_address varchar(500) default null comment '注册地址',
  province varchar(100) default null comment '区域',
  address_postcode varchar(200) default null comment '邮政编码',
  reg_capital double default null comment '注册资本(元)',
  reg_num varchar(100) default null comment '工商登记',
  emp_num varchar(10) default null comment '雇员人数',
  tatolnumber varchar(10) default null comment '管理人员人数',
  law_firm varchar(500) default null comment '律师事务所',
  accountfirm_name varchar(500) default null comment '会计师事务所',
  org_profile text default null comment '公司简介',
  business_scope text default null comment '经营范围',
  found_date datetime default null comment '成立日期',
  listing_date datetime default null comment '上市日期',
  after_issue_pe double default null comment '发行市盈率(倍)',
  online_issue_date datetime default null comment '网上发行日期',
  issue_way varchar(500) default null comment '发行方式',
  par_value double default null comment '每股面值(元)',
  total_issue_num double default null comment '发行量(股)',
  issue_price double default null comment '每股发行价(元)',
  dec_sumissuefee double default null comment '发行费用(元)',
  total_funds double default null comment '发行总市值(元)',
  net_raise_funds double default null comment '募集资金净额(元)',
  open_price double default null comment '首日开盘价(元)',
  close_price double default null comment '首日收盘价(元)',
  turnoverrate double default null comment '首日换手率',
  high_price double default null comment '首日最高价(元)',
  offline_vap_ratio double default null comment '网下配售中签率',
  online_issue_lwr double default null comment '定价中签率',

  primary key (code) using btree
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='公司概况';