/*
 财务分析-杜邦分析
*/
drop table if exists `inv_finance_db`;
create table `inv_finance_db`(
    `id` bigint not null auto_increment comment 'id',
    `security_code` varchar(10) character set utf8mb4 collate utf8mb4_general_ci not null comment '股票代码',
    `report_type` varchar(10) character set utf8mb4 collate utf8mb4_general_ci not null comment '报告类型',
    `report_date` datetime default null comment '报告日期',
    `ROE` double default null comment '净资产收益率(%)',
    `JROA` double default null comment '总资产净利率(%)',
    `PARENT_NETPROFIT_RATIO` double default null comment '归属母公司股东的净利润占比(%)',
    `EQUITY_MULTIPLIER` double default null comment '权益乘数',
    `SALE_NPR` double default null comment '营业净利润率(%)',
    `TOTAL_ASSETS_TR` double default null comment '总资产周转率(%)',
    `DEBT_ASSET_RATIO` double default null comment '资产负债率(%)',
    `NETPROFIT` double default null comment '净利润',
    `TOTAL_OPERATE_INCOME` double default null comment '营业总收入',
    `TOTAL_ASSETS` double default null comment '资产总额',
    `TOTAL_LIABILITIES` double default null comment '负债总额',
    `TOTAL_INCOME` double default null comment '收入总额',
    `TOTAL_COST` double default null comment '成本总额',
    `TOTAL_CURRENT_ASSETS` double default null comment '流动资产',
    `TOTAL_NONCURRENT_ASSETS` double default null comment '非流动资产',
    `INVEST_INCOME` double default null comment '投资收益',
    `ASSET_DISPOSAL_INCOME` double default null comment '资产处置收益',
    `OPERATE_COST` double default null comment '营业成本',
    `OPERATE_TAX_ADD` double default null comment '税金及附加',
    `INCOME_TAX` double default null comment '所得税费用',
    `ASSET_IMPAIRMENT_INCOME` double default null comment '资产减值损失',
    `CREDIT_IMPAIRMENT_INCOME` double default null comment '信用减值损失',
    `NONBUSINESS_EXPENSE` double default null comment '营业外支出',
    `TOTAL_EXPENSE` double default null comment '期间费用',
    `FINANCE_EXPENSE` double default null comment '财务费用',
    `SALE_EXPENSE` double default null comment '销售费用',
    `MANAGE_EXPENSE` double default null comment '管理费用',
    `RESEARCH_EXPENSE` double default null comment '研发费用',
    `MONETARYFUNDS` double default null comment '货币资金',
    `NOTE_RECE` double default null comment '应收票据',
    `ACCOUNTS_RECE` double default null comment '应收账款',
    `FINANCE_RECE` double default null comment '应收款项融资',
    `OTHER_RECE` double default null comment '其他应收款',
    `INVENTORY` double default null comment '存货',
    `OTHER_EQUITY_INVEST` double default null comment '其他权益工具投资',
    `LONG_RECE` double default null comment '长期应收款',
    `LONG_EQUITY_INVEST` double default null comment '长期股权投资',
    `FIXED_ASSET` double default null comment '固定资产',
    `CIP` double default null comment '在建工程',
    `USERIGHT_ASSET` double default null comment '使用权资产',
    `INTANGIBLE_ASSET` double default null comment '无形资产',
    `develop_expense` double default null comment '开发支出',
    `GOODWILL` double default null comment '商誉',
    `LONG_PREPAID_EXPENSE` double default null comment '长期待摊费用',
    `DEFER_TAX_ASSET` double default null comment '递延所得税资产',
    `AVAILABLE_SALE_FINASSET` double default null comment '可供出售金融资产',
    `INTEREST_NI` double default null comment '利息净收入',
    `FEE_COMMISSION_NI` double default null comment '手续费及佣金净收入',
    `FAIRVALUE_CHANGE_INCOME` double default null comment '公允价值变动收益',
    `EXCHANGE_INCOME` double default null comment '汇兑收益',
    `BUSINESS_MANAGE_EXPENSE` double default null comment '业务及管理费',
    `EARNED_PREMIUM` double default null comment '已赚保费',
    `SURRENDER_VALUE` double default null comment '退保金',
    `NET_COMPENSATE_EXPENSE` double default null comment '赔付支出',
    `NET_CONTRACT_RESERVE` double default null comment '提取保险责任准备金',
    `POLICY_BONUS_EXPENSE` double default null comment '保单红利支出',



    `CREDITOR_INVEST` double default null comment '-',
    `INVEST_REALESTATE` double default null comment '-',
    `UPDATE_DATE` double default null comment '-',
    `ORG_TYPE` double default null comment '-',
    `FEE_COMMISSION_EXPENSE` double default null comment '-',
    `ORG_CODE` double default null comment '-',
    `HOLD_MATURITY_INVEST` double default null comment '-',
    `TRADE_FINASSET` double default null comment '-',
    `OTHER_CREDITOR_INVEST` double default null comment '-',
    `SECURITY_NAME_ABBR` double default null comment '-',
    `SECURITY_TYPE_CODE` double default null comment '-',
    `CURRENCY` double default null comment '-',
    `NOTICE_DATE` double default null comment '-',
    `PARENT_NETPROFIT` double default null comment '-',




    primary key (`id`) using btree,
    key `inv_finance_db_key` (`security_code`,`report_type`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-杜邦分析';