/*
财务分析-主要指标
*/
drop table if exists inv_finance_zyzb;
create table inv_finance_zyzb
(
    id                  bigint      not null auto_increment comment 'id',
    security_code       varchar(10) not null comment '股票代码',
    report_type         varchar(10) not null comment '报告类型',
    report_date         datetime    not null comment '报告日期',
    epsjb               double default null comment '摊薄每股收益(元)',
    epskcjb             double default null comment '扣非每股收益(元)',
    epsxs               double default null comment '稀释每股收益(元)',
    bps                 double default null comment '每股净资产(元)',
    mgzbgj              double default null comment '每股公积金(元)',
    mgwfplr             double default null comment '每股未分配利润(元)',
    mgjyxjje            double default null comment '每股经营现金流(元)',
    totaloperatereve    double default null comment '营业总收入(元)',
    mlr                 double default null comment '毛利润(元)',
    parentnetprofit     double default null comment '归属净利润(元)',
    kcfjcxsyjlr         double default null comment '扣非净利润(元)',
    totaloperaterevetz  double default null comment '营业总收入同比增长(%)',
    parentnetprofittz   double default null comment '归属净利润同比增长(%)',
    kcfjcxsyjlrtz       double default null comment '扣非净利润同比增长(%)',
    yyzsrgdhbzc         double default null comment '营业总收入滚动环比增长(%)',
    netprofitrphbzc     double default null comment '归属净利润滚动环比增长(%)',
    kfjlrgdhbzc         double default null comment '扣非净利润滚动环比增长(%)',
    roejq               double default null comment '净资产收益率(加权)(%)',
    roekcjq             double default null comment '净资产收益率(扣非/加权)(%)',
    zzcjll              double default null comment '总资产收益率(加权)(%)',
    xsmll               double default null comment '毛利率(%)',
    xsjll               double default null comment '净利率(%)',
    yszkyysr            double default null comment '预收账款/营业总收入',
    xsjxlyysr           double default null comment '销售净现金流/营业总收入',
    jyxjlyysr           double default null comment '经营净现金流/营业总收入',
    taxrate             double default null comment '实际税率(%)',
    ld                  double default null comment '流动比率',
    sd                  double default null comment '速动比率',
    xjllb               double default null comment '现金流量比率',
    zcfzl               double default null comment '资产负债率(%)',
    qycs                double default null comment '权益乘数',
    cqbl                double default null comment '产权比率',
    zzczzts             double default null comment '总资产周转天数(天)',
    chzzts              double default null comment '存货周转天数(天)',
    yszkzzts            double default null comment '应收账款周转天数(天)',
    toazzl              double default null comment '总资产周转率(次)',
    chzzl               double default null comment '存货周转率(次)',
    yszkzzl             double default null comment '应收账款周转率(次)',
    totaldeposits       double default null comment '存款总额(元)',
    grossloans          double default null comment '贷款总额(元)',
    ltdrr               double default null comment '存贷款比例',
    newcapitalader      double default null comment '资本充足率(%)',
    hxyjbczl            double default null comment '核心资本充足率(%)',
    nonperloan          double default null comment '不良贷款率(%)',
    bldkbbl             double default null comment '不良贷款拨备覆盖率(%)',
    nzbje               double default null comment '资本净额(元)',
    total_roi           double default null comment '总投资收益率(%)',
    net_roi             double default null comment '净投资收益率(%)',
    earned_premium      double default null comment '已赚保费(元)',
    compensate_expense  double default null comment '赔付支出(元)',
    surrender_rate_life double default null comment '退保率(%)',
    solvency_ar         double default null comment '偿付能力充足率(%)',
    jzb                 double default null comment '净资本(元)',
    jzc                 double default null comment '净资产(元)',
    jzbjzc              double default null comment '净资本/净资产',
    zygpgmjzc           double default null comment '自营股票规模/净资产',
    zygdsylzqjzb        double default null comment '自营固定收益类证券规模/净资产',
    yyfxzb              double default null comment '营运风险准备(元)',
    jjywfxzb            double default null comment '经纪业务风险准备(元)',
    zqzyywfxzb          double default null comment '证券自营业务风险准备(元)',
    zqcxywfxzb          double default null comment '证券承销业务风险准备(元)',
    rzrqywfxzb          double default null comment '融资融券业务风险准备(元)',
    per_capital_reserve double default null comment '每股公积金(元)',
    per_unassign_profit double default null comment '每股未分配利润(元)',
    per_netcash         double default null comment '每股经营现金流(元)',
    gross_profit        double default null comment '毛利润(元)',
    dedu_parent_profit  double default null comment '扣非净利润(元)',
    dpnp_yoy_ratio      double default null comment '扣非净利润同比增长(%)',
    roe_diluted         double default null comment '摊薄净资产收益率(%)',
    jroa                double default null comment '摊薄总资产收益率(%)',
    gross_profit_ratio  double default null comment '毛利率(%)',
    net_profit_ratio    double default null comment '净利率(%)',
    primary key (id) using btree,
    key                 inv_finance_zyzb_index (security_code,report_type)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-主要指标';