/*
 财务分析-百分比
*/
drop table if exists inv_finance_bfb;
create table inv_finance_bfb
(
    id                          int         not null auto_increment comment 'ID',
    security_code               varchar(10) not null comment '股票代码',
    report_type                 varchar(10) not null comment '报告类型',
    report_date                 datetime default null comment '报告日期',
    total_assets                double   default null comment '总资产',
    operate_income              double   default null comment '一、营业收入(元)',
    total_current_assets        double   default null comment '流动资产',
    interest_ni                 double   default null comment '利息净收入(元)',
    fee_commission_ni           double   default null comment '手续费及佣金净收入(元)',
    total_noncurrent_assets     double   default null comment '非流动资产',
    invest_income               double   default null comment '投资收益(元)',
    total_liabilities           double   default null comment '总负债金额',
    fairvalue_change_income     double   default null comment '公允价值变动收益(元)',
    total_current_liab          double   default null comment '流动负债',
    exchange_income             double   default null comment '汇兑收益(元)',
    other_business_income       double   default null comment '其他业务收入(元)',
    total_noncurrent_liab       double   default null comment '非流动负债',
    asset_disposal_income       double   default null comment '资产处置收益(元)',
    other_income                double   default null comment '其他收益(元)',
    operate_expense             double   default null comment '二、营业支出(元)',
    operate_tax_add             double   default null comment '税金及附加(元)',
    business_manage_expense     double   default null comment '业务及管理费(元)',
    asset_impairment_loss       double   default null comment '资产减值损失(元)',
    credit_impairment_loss      double   default null comment '信用减值损失(元)',
    other_business_cost         double   default null comment '其他业务成本(元)',
    operate_profit              double   default null comment '三、营业利润(元)',
    nonbusiness_income          double   default null comment '加:营业外收入(元)',
    nonbusiness_expense         double   default null comment '减:营业外支出(元)',
    total_profit                double   default null comment '四、利润总额(元)',
    income_tax                  double   default null comment '减:所得税费用(元)',
    netprofit                   double   default null comment '五、净利润(元)',
    total_operate_income        double   default null comment '一、营业总收入(元)',
    total_operate_cost          double   default null comment '二、营业总成本(元)',
    operate_cost                double   default null comment '营业成本(元)',
    total_expense               double   default null comment '期间费用(元)',
    sale_expense                double   default null comment '销售费用(元)',
    manage_expense              double   default null comment '管理费用(元)',
    research_expense            double   default null comment '研发费用(元)',
    finance_expense             double   default null comment '财务费用(元)',
    credit_impairment_income    double   default null comment '信用减值损失(元)',
    asset_impairment_income     double   default null comment '资产减值损失(元)',
    earned_premium              double   default null comment '已赚保费(元)',
    fairvalue_change            double   default null comment '公允价值变动收益(元)',
    surrender_value             double   default null comment '退保金(元)',
    compensate_expense          double   default null comment '赔付支出(元)',
    amortize_compensate_expense double   default null comment '减:摊回赔付支出(元)',
    extract_insurance_reserve   double   default null comment '提取保险责任准备金(元)',
    amortize_insurance_reserve  double   default null comment '减:摊回保险责任准备金(元)',
    policy_bonus_expense        double   default null comment '保单红利支出(元)',
    fee_commission_expense      double   default null comment '手续费及佣金支出(元)',
    primary key (id) using btree,
    key                         inv_finance_bfb_index (security_code,report_type)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-百分比表';
