/*
 财务分析-百分比
*/
drop table if exists `inv_finance_bfb`;
create table `inv_finance_bfb`(
    `id` bigint not null auto_increment comment 'id',
    `security_code` varchar(10) character set utf8mb4 collate utf8mb4_general_ci not null comment '股票代码',
    `report_type` varchar(10) character set utf8mb4 collate utf8mb4_general_ci not null comment '报告类型',
    `report_date` datetime default null comment '报告日期',
    `operate_income` double default null comment '营业收入',
    `operate_income_yoy` double default null comment '营业收入(占比%)',
    `interest_ni` double default null comment '利息净收入',
    `interest_ni_yoy` double default null comment '利息净收入(占比%)',
    `fee_commission_ni` double default null comment '手续费及佣金净收入',
    `fee_commission_ni_yoy` double default null comment '手续费及佣金净收入(占比%)',
    `invest_income` double default null comment '投资收益',
    `invest_income_yoy` double default null comment '投资收益(占比%)',
    `fairvalue_change_income` double default null comment '公允价值变动收益',
    `fairvalue_change_income_yoy` double default null comment '公允价值变动收益(占比%)',
    `exchange_income` double default null comment '汇兑收益',
    `exchange_income_yoy` double default null comment '汇兑收益(占比%)',
    `other_business_income` double default null comment '其他业务收入',
    `other_business_income_yoy` double default null comment '其他业务收入(占比%)',
    `asset_disposal_income` double default null comment '资产处置收益',
    `asset_disposal_income_yoy` double default null comment '资产处置收益(占比%)',
    `other_income` double default null comment '其他收益',
    `other_income_yoy` double default null comment '其他收益(占比%)',
    `operate_expense` double default null comment '营业支出',
    `operate_expense_yoy` double default null comment '营业支出(占比%)',
    `operate_tax_add` double default null comment '税金及附加',
    `operate_tax_add_yoy` double default null comment '税金及附加(占比%)',
    `business_manage_expense` double default null comment '业务及管理费',
    `business_manage_expense_yoy` double default null comment '业务及管理费(占比%)',
    `asset_impairment_loss` double default null comment '资产减值损失',
    `asset_impairment_loss_yoy` double default null comment '资产减值损失(占比%)',
    `credit_impairment_loss` double default null comment '信用减值损失',
    `credit_impairment_loss_yoy` double default null comment '信用减值损失(占比%)',
    `other_business_cost` double default null comment '其他业务成本',
    `other_business_cost_yoy` double default null comment '其他业务成本(占比%)',
    `operate_profit` double default null comment '营业利润',
    `operate_profit_yoy` double default null comment '营业利润(占比%)',
    `nonbusiness_income` double default null comment '营业外收入',
    `nonbusiness_income_yoy` double default null comment '营业外收入(占比%)',
    `nonbusiness_expense` double default null comment '营业外支出',
    `nonbusiness_expense_yoy` double default null comment '营业外支出(占比%)',
    `total_profit` double default null comment '利润总额',
    `total_profit_yoy` double default null comment '利润总额(占比%)',
    `income_tax` double default null comment '所得税费用',
    `income_tax_yoy` double default null comment '所得税费用(占比%)',
    `netprofit` double default null comment '净利润',
    `netprofit_yoy` double default null comment '净利润(占比%)',
    primary key (`id`) using btree,
    key `inv_finance_bfb_index` (`security_code`,`report_type`)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-百分比表';
