/*
 财务分析-杜邦分析
*/
drop table if exists inv_finance_dbfx;
create table inv_finance_dbfx
(
    id                       int         not null auto_increment comment 'id',
    security_code            varchar(10) not null comment '股票代码',
    report_type              varchar(10) not null comment '报告类型',
    report_date              datetime default null comment '报告日期',
    roe                      double   default null comment '净资产收益率(%)',
    jroa                     double   default null comment '总资产净利率(%)',
    parent_netprofit_ratio   double   default null comment '归属母公司股东的净利润占比(%)',
    equity_multiplier        double   default null comment '权益乘数',
    sale_npr                 double   default null comment '营业净利润率(%)',
    total_assets_tr          double   default null comment '总资产周转率(%)',
    debt_asset_ratio         double   default null comment '资产负债率(%)',
    netprofit                double   default null comment '净利润',
    total_assets             double   default null comment '资产总额',
    total_liabilities        double   default null comment '负债总额',
    total_income             double   default null comment '收入总额',
    total_cost               double   default null comment '成本总额',
    total_current_assets     double   default null comment '流动资产',
    total_noncurrent_assets  double   default null comment '非流动资产',
    operate_cost             double   default null comment '营业成本',
    total_expense            double   default null comment '期间费用',
    monetaryfunds            double   default null comment '货币资金',
    creditor_invest          double   default null comment '债权投资',
    useright_asset           double   default null comment '使用权资产',
    total_operate_income     double   default null comment '营业总收入',
    invest_income            double   default null comment '投资收益',
    operate_tax_add          double   default null comment '税金及附加',
    trade_finasset           double   default null comment '交易性金融资产',
    other_creditor_invest    double   default null comment '其他债权投资',
    intangible_asset         double   default null comment '无形资产',
    fairvalue_change_income  double   default null comment '公允价值变动收益',
    income_tax               double   default null comment '所得税费用',
    finance_expense          double   default null comment '财务费用',
    note_rece                double   default null comment '应收票据',
    other_equity_invest      double   default null comment '其他权益工具投资',
    develop_expense          double   default null comment '开发支出',
    asset_disposal_income    double   default null comment '资产处置收益',
    asset_impairment_income  double   default null comment '资产减值损失',
    sale_expense             double   default null comment '销售费用',
    accounts_rece            double   default null comment '应收账款',
    long_rece                double   default null comment '长期应收款',
    goodwill                 double   default null comment '商誉',
    exchange_income          double   default null comment '汇兑收益',
    credit_impairment_income double   default null comment '信用减值损失',
    manage_expense           double   default null comment '管理费用',
    finance_rece             double   default null comment '应收款项融资',
    long_equity_invest       double   default null comment '长期股权投资',
    long_prepaid_expense     double   default null comment '长期待摊费用',
    nonbusiness_expense      double   default null comment '营业外支出',
    research_expense         double   default null comment '研发费用',
    other_rece               double   default null comment '其他应收款',
    invest_realestate        double   default null comment '投资性房地产',
    defer_tax_asset          double   default null comment '递延所得税资产',
    inventory                double   default null comment '存货',
    fixed_asset              double   default null comment '固定资产',
    available_sale_finasset  double   default null comment '可供出售金融资产',
    cip                      double   default null comment '在建工程',
    hold_maturity_invest     double   default null comment '持有至到期投资',
    earned_premium           double   default null comment '已赚保费',
    surrender_value          double   default null comment '退保金',
    net_compensate_expense   double   default null comment '赔付支出',
    net_contract_reserve     double   default null comment '提取保险责任准备金',
    policy_bonus_expense     double   default null comment '保单红利支出',
    interest_ni              double   default null comment '利息净收入',
    fee_commission_ni        double   default null comment '手续费及佣金净收入',
    business_manage_expense  double   default null comment '业务及管理费',
    fee_commission_expense   double   default null comment '手续费及佣金支出',
    parent_netprofit         double   default null comment '归属于母公司股东的净利润',
    primary key (id) using btree,
    key                      inv_finance_dbfx_index (security_code,report_type)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci comment='财务分析-杜邦分析';